/*
Figshare API

Testing ArticlesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package go_figshare

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_go_figshare_ArticlesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ArticlesAPIService ArticleDetails", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var articleId int64

		resp, httpRes, err := apiClient.ArticlesAPI.ArticleDetails(context.Background(), articleId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ArticlesAPIService ArticlesList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ArticlesAPI.ArticlesList(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ArticlesAPIService CrawlTotalArticle", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var articleId int64

		resp, httpRes, err := apiClient.ArticlesAPI.CrawlTotalArticle(context.Background(), articleId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ArticlesAPIService GetAggregatedCitations", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ArticlesAPI.GetAggregatedCitations(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
