/*
Figshare API

Figshare apiv2. Using Swagger 2.0

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package figshare

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ArticleWithProject type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ArticleWithProject{}

// ArticleWithProject struct for ArticleWithProject
type ArticleWithProject struct {
	// Project id for this article.
	ProjectId int64 `json:"project_id"`
	// Date when article was created
	CreatedDate string `json:"created_date"`
	// Type of article identifier
	DefinedType int64 `json:"defined_type"`
	// Name of the article type identifier
	DefinedTypeName string `json:"defined_type_name"`
	// DOI
	Doi string `json:"doi"`
	// Handle
	Handle string `json:"handle"`
	// Unique identifier for article
	Id int64 `json:"id"`
	// Deprecated by related materials. Not applicable to regular users. In a publisher case, this is the publisher article DOI.
	ResourceDoi string `json:"resource_doi"`
	// Deprecated by related materials. Not applicable to regular users. In a publisher case, this is the publisher article title.
	ResourceTitle string `json:"resource_title"`
	// Thumbnail image
	Thumb string `json:"thumb"`
	Timeline Timeline `json:"timeline"`
	// Title of article
	Title string `json:"title"`
	// Api endpoint for article
	Url string `json:"url"`
	// Private Api endpoint for article
	UrlPrivateApi string `json:"url_private_api"`
	// Private site endpoint for article
	UrlPrivateHtml string `json:"url_private_html"`
	// Public Api endpoint for article
	UrlPublicApi string `json:"url_public_api"`
	// Public site endpoint for article
	UrlPublicHtml string `json:"url_public_html"`
}

type _ArticleWithProject ArticleWithProject

// NewArticleWithProject instantiates a new ArticleWithProject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewArticleWithProject(projectId int64, createdDate string, definedType int64, definedTypeName string, doi string, handle string, id int64, resourceDoi string, resourceTitle string, thumb string, timeline Timeline, title string, url string, urlPrivateApi string, urlPrivateHtml string, urlPublicApi string, urlPublicHtml string) *ArticleWithProject {
	this := ArticleWithProject{}
	this.CreatedDate = createdDate
	this.DefinedType = definedType
	this.DefinedTypeName = definedTypeName
	this.Doi = doi
	this.Handle = handle
	this.Id = id
	this.ResourceDoi = resourceDoi
	this.ResourceTitle = resourceTitle
	this.Thumb = thumb
	this.Timeline = timeline
	this.Title = title
	this.Url = url
	this.UrlPrivateApi = urlPrivateApi
	this.UrlPrivateHtml = urlPrivateHtml
	this.UrlPublicApi = urlPublicApi
	this.UrlPublicHtml = urlPublicHtml
	return &this
}

// NewArticleWithProjectWithDefaults instantiates a new ArticleWithProject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewArticleWithProjectWithDefaults() *ArticleWithProject {
	this := ArticleWithProject{}
	var projectId int64 = 0
	this.ProjectId = projectId
	var resourceDoi string = ""
	this.ResourceDoi = resourceDoi
	var resourceTitle string = ""
	this.ResourceTitle = resourceTitle
	return &this
}

// GetProjectId returns the ProjectId field value
func (o *ArticleWithProject) GetProjectId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *ArticleWithProject) GetProjectIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *ArticleWithProject) SetProjectId(v int64) {
	o.ProjectId = v
}

// GetCreatedDate returns the CreatedDate field value
func (o *ArticleWithProject) GetCreatedDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedDate
}

// GetCreatedDateOk returns a tuple with the CreatedDate field value
// and a boolean to check if the value has been set.
func (o *ArticleWithProject) GetCreatedDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedDate, true
}

// SetCreatedDate sets field value
func (o *ArticleWithProject) SetCreatedDate(v string) {
	o.CreatedDate = v
}

// GetDefinedType returns the DefinedType field value
func (o *ArticleWithProject) GetDefinedType() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.DefinedType
}

// GetDefinedTypeOk returns a tuple with the DefinedType field value
// and a boolean to check if the value has been set.
func (o *ArticleWithProject) GetDefinedTypeOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DefinedType, true
}

// SetDefinedType sets field value
func (o *ArticleWithProject) SetDefinedType(v int64) {
	o.DefinedType = v
}

// GetDefinedTypeName returns the DefinedTypeName field value
func (o *ArticleWithProject) GetDefinedTypeName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DefinedTypeName
}

// GetDefinedTypeNameOk returns a tuple with the DefinedTypeName field value
// and a boolean to check if the value has been set.
func (o *ArticleWithProject) GetDefinedTypeNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DefinedTypeName, true
}

// SetDefinedTypeName sets field value
func (o *ArticleWithProject) SetDefinedTypeName(v string) {
	o.DefinedTypeName = v
}

// GetDoi returns the Doi field value
func (o *ArticleWithProject) GetDoi() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Doi
}

// GetDoiOk returns a tuple with the Doi field value
// and a boolean to check if the value has been set.
func (o *ArticleWithProject) GetDoiOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Doi, true
}

// SetDoi sets field value
func (o *ArticleWithProject) SetDoi(v string) {
	o.Doi = v
}

// GetHandle returns the Handle field value
func (o *ArticleWithProject) GetHandle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Handle
}

// GetHandleOk returns a tuple with the Handle field value
// and a boolean to check if the value has been set.
func (o *ArticleWithProject) GetHandleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Handle, true
}

// SetHandle sets field value
func (o *ArticleWithProject) SetHandle(v string) {
	o.Handle = v
}

// GetId returns the Id field value
func (o *ArticleWithProject) GetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ArticleWithProject) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ArticleWithProject) SetId(v int64) {
	o.Id = v
}

// GetResourceDoi returns the ResourceDoi field value
func (o *ArticleWithProject) GetResourceDoi() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResourceDoi
}

// GetResourceDoiOk returns a tuple with the ResourceDoi field value
// and a boolean to check if the value has been set.
func (o *ArticleWithProject) GetResourceDoiOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResourceDoi, true
}

// SetResourceDoi sets field value
func (o *ArticleWithProject) SetResourceDoi(v string) {
	o.ResourceDoi = v
}

// GetResourceTitle returns the ResourceTitle field value
func (o *ArticleWithProject) GetResourceTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResourceTitle
}

// GetResourceTitleOk returns a tuple with the ResourceTitle field value
// and a boolean to check if the value has been set.
func (o *ArticleWithProject) GetResourceTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResourceTitle, true
}

// SetResourceTitle sets field value
func (o *ArticleWithProject) SetResourceTitle(v string) {
	o.ResourceTitle = v
}

// GetThumb returns the Thumb field value
func (o *ArticleWithProject) GetThumb() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Thumb
}

// GetThumbOk returns a tuple with the Thumb field value
// and a boolean to check if the value has been set.
func (o *ArticleWithProject) GetThumbOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Thumb, true
}

// SetThumb sets field value
func (o *ArticleWithProject) SetThumb(v string) {
	o.Thumb = v
}

// GetTimeline returns the Timeline field value
func (o *ArticleWithProject) GetTimeline() Timeline {
	if o == nil {
		var ret Timeline
		return ret
	}

	return o.Timeline
}

// GetTimelineOk returns a tuple with the Timeline field value
// and a boolean to check if the value has been set.
func (o *ArticleWithProject) GetTimelineOk() (*Timeline, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timeline, true
}

// SetTimeline sets field value
func (o *ArticleWithProject) SetTimeline(v Timeline) {
	o.Timeline = v
}

// GetTitle returns the Title field value
func (o *ArticleWithProject) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *ArticleWithProject) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *ArticleWithProject) SetTitle(v string) {
	o.Title = v
}

// GetUrl returns the Url field value
func (o *ArticleWithProject) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *ArticleWithProject) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *ArticleWithProject) SetUrl(v string) {
	o.Url = v
}

// GetUrlPrivateApi returns the UrlPrivateApi field value
func (o *ArticleWithProject) GetUrlPrivateApi() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UrlPrivateApi
}

// GetUrlPrivateApiOk returns a tuple with the UrlPrivateApi field value
// and a boolean to check if the value has been set.
func (o *ArticleWithProject) GetUrlPrivateApiOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UrlPrivateApi, true
}

// SetUrlPrivateApi sets field value
func (o *ArticleWithProject) SetUrlPrivateApi(v string) {
	o.UrlPrivateApi = v
}

// GetUrlPrivateHtml returns the UrlPrivateHtml field value
func (o *ArticleWithProject) GetUrlPrivateHtml() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UrlPrivateHtml
}

// GetUrlPrivateHtmlOk returns a tuple with the UrlPrivateHtml field value
// and a boolean to check if the value has been set.
func (o *ArticleWithProject) GetUrlPrivateHtmlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UrlPrivateHtml, true
}

// SetUrlPrivateHtml sets field value
func (o *ArticleWithProject) SetUrlPrivateHtml(v string) {
	o.UrlPrivateHtml = v
}

// GetUrlPublicApi returns the UrlPublicApi field value
func (o *ArticleWithProject) GetUrlPublicApi() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UrlPublicApi
}

// GetUrlPublicApiOk returns a tuple with the UrlPublicApi field value
// and a boolean to check if the value has been set.
func (o *ArticleWithProject) GetUrlPublicApiOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UrlPublicApi, true
}

// SetUrlPublicApi sets field value
func (o *ArticleWithProject) SetUrlPublicApi(v string) {
	o.UrlPublicApi = v
}

// GetUrlPublicHtml returns the UrlPublicHtml field value
func (o *ArticleWithProject) GetUrlPublicHtml() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UrlPublicHtml
}

// GetUrlPublicHtmlOk returns a tuple with the UrlPublicHtml field value
// and a boolean to check if the value has been set.
func (o *ArticleWithProject) GetUrlPublicHtmlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UrlPublicHtml, true
}

// SetUrlPublicHtml sets field value
func (o *ArticleWithProject) SetUrlPublicHtml(v string) {
	o.UrlPublicHtml = v
}

func (o ArticleWithProject) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ArticleWithProject) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["project_id"] = o.ProjectId
	toSerialize["created_date"] = o.CreatedDate
	toSerialize["defined_type"] = o.DefinedType
	toSerialize["defined_type_name"] = o.DefinedTypeName
	toSerialize["doi"] = o.Doi
	toSerialize["handle"] = o.Handle
	toSerialize["id"] = o.Id
	toSerialize["resource_doi"] = o.ResourceDoi
	toSerialize["resource_title"] = o.ResourceTitle
	toSerialize["thumb"] = o.Thumb
	toSerialize["timeline"] = o.Timeline
	toSerialize["title"] = o.Title
	toSerialize["url"] = o.Url
	toSerialize["url_private_api"] = o.UrlPrivateApi
	toSerialize["url_private_html"] = o.UrlPrivateHtml
	toSerialize["url_public_api"] = o.UrlPublicApi
	toSerialize["url_public_html"] = o.UrlPublicHtml
	return toSerialize, nil
}

func (o *ArticleWithProject) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"project_id",
		"created_date",
		"defined_type",
		"defined_type_name",
		"doi",
		"handle",
		"id",
		"resource_doi",
		"resource_title",
		"thumb",
		"timeline",
		"title",
		"url",
		"url_private_api",
		"url_private_html",
		"url_public_api",
		"url_public_html",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varArticleWithProject := _ArticleWithProject{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varArticleWithProject)

	if err != nil {
		return err
	}

	*o = ArticleWithProject(varArticleWithProject)

	return err
}

type NullableArticleWithProject struct {
	value *ArticleWithProject
	isSet bool
}

func (v NullableArticleWithProject) Get() *ArticleWithProject {
	return v.value
}

func (v *NullableArticleWithProject) Set(val *ArticleWithProject) {
	v.value = val
	v.isSet = true
}

func (v NullableArticleWithProject) IsSet() bool {
	return v.isSet
}

func (v *NullableArticleWithProject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableArticleWithProject(val *ArticleWithProject) *NullableArticleWithProject {
	return &NullableArticleWithProject{value: val, isSet: true}
}

func (v NullableArticleWithProject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableArticleWithProject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


