/*
Figshare API

Figshare apiv2. Using Swagger 2.0

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package figshare

import (
	"encoding/json"
)

// checks if the TimelineUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TimelineUpdate{}

// TimelineUpdate struct for TimelineUpdate
type TimelineUpdate struct {
	// Online posted date
	FirstOnline *string `json:"firstOnline,omitempty"`
	// Date when the item was accepted for publication
	PublisherAcceptance *string `json:"publisherAcceptance,omitempty"`
	// Publish date
	PublisherPublication *string `json:"publisherPublication,omitempty"`
}

// NewTimelineUpdate instantiates a new TimelineUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTimelineUpdate() *TimelineUpdate {
	this := TimelineUpdate{}
	return &this
}

// NewTimelineUpdateWithDefaults instantiates a new TimelineUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTimelineUpdateWithDefaults() *TimelineUpdate {
	this := TimelineUpdate{}
	return &this
}

// GetFirstOnline returns the FirstOnline field value if set, zero value otherwise.
func (o *TimelineUpdate) GetFirstOnline() string {
	if o == nil || IsNil(o.FirstOnline) {
		var ret string
		return ret
	}
	return *o.FirstOnline
}

// GetFirstOnlineOk returns a tuple with the FirstOnline field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineUpdate) GetFirstOnlineOk() (*string, bool) {
	if o == nil || IsNil(o.FirstOnline) {
		return nil, false
	}
	return o.FirstOnline, true
}

// HasFirstOnline returns a boolean if a field has been set.
func (o *TimelineUpdate) HasFirstOnline() bool {
	if o != nil && !IsNil(o.FirstOnline) {
		return true
	}

	return false
}

// SetFirstOnline gets a reference to the given string and assigns it to the FirstOnline field.
func (o *TimelineUpdate) SetFirstOnline(v string) {
	o.FirstOnline = &v
}

// GetPublisherAcceptance returns the PublisherAcceptance field value if set, zero value otherwise.
func (o *TimelineUpdate) GetPublisherAcceptance() string {
	if o == nil || IsNil(o.PublisherAcceptance) {
		var ret string
		return ret
	}
	return *o.PublisherAcceptance
}

// GetPublisherAcceptanceOk returns a tuple with the PublisherAcceptance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineUpdate) GetPublisherAcceptanceOk() (*string, bool) {
	if o == nil || IsNil(o.PublisherAcceptance) {
		return nil, false
	}
	return o.PublisherAcceptance, true
}

// HasPublisherAcceptance returns a boolean if a field has been set.
func (o *TimelineUpdate) HasPublisherAcceptance() bool {
	if o != nil && !IsNil(o.PublisherAcceptance) {
		return true
	}

	return false
}

// SetPublisherAcceptance gets a reference to the given string and assigns it to the PublisherAcceptance field.
func (o *TimelineUpdate) SetPublisherAcceptance(v string) {
	o.PublisherAcceptance = &v
}

// GetPublisherPublication returns the PublisherPublication field value if set, zero value otherwise.
func (o *TimelineUpdate) GetPublisherPublication() string {
	if o == nil || IsNil(o.PublisherPublication) {
		var ret string
		return ret
	}
	return *o.PublisherPublication
}

// GetPublisherPublicationOk returns a tuple with the PublisherPublication field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineUpdate) GetPublisherPublicationOk() (*string, bool) {
	if o == nil || IsNil(o.PublisherPublication) {
		return nil, false
	}
	return o.PublisherPublication, true
}

// HasPublisherPublication returns a boolean if a field has been set.
func (o *TimelineUpdate) HasPublisherPublication() bool {
	if o != nil && !IsNil(o.PublisherPublication) {
		return true
	}

	return false
}

// SetPublisherPublication gets a reference to the given string and assigns it to the PublisherPublication field.
func (o *TimelineUpdate) SetPublisherPublication(v string) {
	o.PublisherPublication = &v
}

func (o TimelineUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TimelineUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FirstOnline) {
		toSerialize["firstOnline"] = o.FirstOnline
	}
	if !IsNil(o.PublisherAcceptance) {
		toSerialize["publisherAcceptance"] = o.PublisherAcceptance
	}
	if !IsNil(o.PublisherPublication) {
		toSerialize["publisherPublication"] = o.PublisherPublication
	}
	return toSerialize, nil
}

type NullableTimelineUpdate struct {
	value *TimelineUpdate
	isSet bool
}

func (v NullableTimelineUpdate) Get() *TimelineUpdate {
	return v.value
}

func (v *NullableTimelineUpdate) Set(val *TimelineUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableTimelineUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableTimelineUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTimelineUpdate(val *TimelineUpdate) *NullableTimelineUpdate {
	return &NullableTimelineUpdate{value: val, isSet: true}
}

func (v NullableTimelineUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTimelineUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


