/*
Figshare API

Figshare apiv2. Using Swagger 2.0

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package go_figshare

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ResponseMessage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseMessage{}

// ResponseMessage struct for ResponseMessage
type ResponseMessage struct {
	// Response message text
	Message string `json:"message"`
}

type _ResponseMessage ResponseMessage

// NewResponseMessage instantiates a new ResponseMessage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseMessage(message string) *ResponseMessage {
	this := ResponseMessage{}
	this.Message = message
	return &this
}

// NewResponseMessageWithDefaults instantiates a new ResponseMessage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseMessageWithDefaults() *ResponseMessage {
	this := ResponseMessage{}
	return &this
}

// GetMessage returns the Message field value
func (o *ResponseMessage) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *ResponseMessage) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *ResponseMessage) SetMessage(v string) {
	o.Message = v
}

func (o ResponseMessage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseMessage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	return toSerialize, nil
}

func (o *ResponseMessage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResponseMessage := _ResponseMessage{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varResponseMessage)

	if err != nil {
		return err
	}

	*o = ResponseMessage(varResponseMessage)

	return err
}

type NullableResponseMessage struct {
	value *ResponseMessage
	isSet bool
}

func (v NullableResponseMessage) Get() *ResponseMessage {
	return v.value
}

func (v *NullableResponseMessage) Set(val *ResponseMessage) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseMessage) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseMessage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseMessage(val *ResponseMessage) *NullableResponseMessage {
	return &NullableResponseMessage{value: val, isSet: true}
}

func (v NullableResponseMessage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseMessage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


