/*
Figshare API

Figshare apiv2. Using Swagger 2.0

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package go_figshare

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Category type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Category{}

// Category struct for Category
type Category struct {
	// Parent category
	ParentId int64 `json:"parent_id"`
	// Category id
	Id int64 `json:"id"`
	// Category title
	Title string `json:"title"`
	// Path to all ancestor ids
	Path string `json:"path"`
	// ID in original standard taxonomy
	SourceId string `json:"source_id"`
	// Internal id of taxonomy the category is part of
	TaxonomyId int64 `json:"taxonomy_id"`
}

type _Category Category

// NewCategory instantiates a new Category object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCategory(parentId int64, id int64, title string, path string, sourceId string, taxonomyId int64) *Category {
	this := Category{}
	this.ParentId = parentId
	this.Id = id
	this.Title = title
	this.Path = path
	this.SourceId = sourceId
	this.TaxonomyId = taxonomyId
	return &this
}

// NewCategoryWithDefaults instantiates a new Category object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCategoryWithDefaults() *Category {
	this := Category{}
	return &this
}

// GetParentId returns the ParentId field value
func (o *Category) GetParentId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ParentId
}

// GetParentIdOk returns a tuple with the ParentId field value
// and a boolean to check if the value has been set.
func (o *Category) GetParentIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ParentId, true
}

// SetParentId sets field value
func (o *Category) SetParentId(v int64) {
	o.ParentId = v
}

// GetId returns the Id field value
func (o *Category) GetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Category) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Category) SetId(v int64) {
	o.Id = v
}

// GetTitle returns the Title field value
func (o *Category) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *Category) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *Category) SetTitle(v string) {
	o.Title = v
}

// GetPath returns the Path field value
func (o *Category) GetPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Path
}

// GetPathOk returns a tuple with the Path field value
// and a boolean to check if the value has been set.
func (o *Category) GetPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Path, true
}

// SetPath sets field value
func (o *Category) SetPath(v string) {
	o.Path = v
}

// GetSourceId returns the SourceId field value
func (o *Category) GetSourceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceId
}

// GetSourceIdOk returns a tuple with the SourceId field value
// and a boolean to check if the value has been set.
func (o *Category) GetSourceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceId, true
}

// SetSourceId sets field value
func (o *Category) SetSourceId(v string) {
	o.SourceId = v
}

// GetTaxonomyId returns the TaxonomyId field value
func (o *Category) GetTaxonomyId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.TaxonomyId
}

// GetTaxonomyIdOk returns a tuple with the TaxonomyId field value
// and a boolean to check if the value has been set.
func (o *Category) GetTaxonomyIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TaxonomyId, true
}

// SetTaxonomyId sets field value
func (o *Category) SetTaxonomyId(v int64) {
	o.TaxonomyId = v
}

func (o Category) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Category) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["parent_id"] = o.ParentId
	toSerialize["id"] = o.Id
	toSerialize["title"] = o.Title
	toSerialize["path"] = o.Path
	toSerialize["source_id"] = o.SourceId
	toSerialize["taxonomy_id"] = o.TaxonomyId
	return toSerialize, nil
}

func (o *Category) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"parent_id",
		"id",
		"title",
		"path",
		"source_id",
		"taxonomy_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCategory := _Category{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCategory)

	if err != nil {
		return err
	}

	*o = Category(varCategory)

	return err
}

type NullableCategory struct {
	value *Category
	isSet bool
}

func (v NullableCategory) Get() *Category {
	return v.value
}

func (v *NullableCategory) Set(val *Category) {
	v.value = val
	v.isSet = true
}

func (v NullableCategory) IsSet() bool {
	return v.isSet
}

func (v *NullableCategory) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCategory(val *Category) *NullableCategory {
	return &NullableCategory{value: val, isSet: true}
}

func (v NullableCategory) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCategory) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


