/*
Figshare API

Figshare apiv2. Using Swagger 2.0

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package go_figshare

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AuthorsCreator type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthorsCreator{}

// AuthorsCreator struct for AuthorsCreator
type AuthorsCreator struct {
	// List of authors to be associated with the article. The list can contain the following fields: id, name, first_name, last_name, email, orcid_id. If an id is supplied, it will take priority and everything else will be ignored. For adding more authors use the specific authors endpoint.
	Authors []map[string]interface{} `json:"authors"`
}

type _AuthorsCreator AuthorsCreator

// NewAuthorsCreator instantiates a new AuthorsCreator object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthorsCreator(authors []map[string]interface{}) *AuthorsCreator {
	this := AuthorsCreator{}
	this.Authors = authors
	return &this
}

// NewAuthorsCreatorWithDefaults instantiates a new AuthorsCreator object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthorsCreatorWithDefaults() *AuthorsCreator {
	this := AuthorsCreator{}
	return &this
}

// GetAuthors returns the Authors field value
func (o *AuthorsCreator) GetAuthors() []map[string]interface{} {
	if o == nil {
		var ret []map[string]interface{}
		return ret
	}

	return o.Authors
}

// GetAuthorsOk returns a tuple with the Authors field value
// and a boolean to check if the value has been set.
func (o *AuthorsCreator) GetAuthorsOk() ([]map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.Authors, true
}

// SetAuthors sets field value
func (o *AuthorsCreator) SetAuthors(v []map[string]interface{}) {
	o.Authors = v
}

func (o AuthorsCreator) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthorsCreator) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["authors"] = o.Authors
	return toSerialize, nil
}

func (o *AuthorsCreator) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"authors",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAuthorsCreator := _AuthorsCreator{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAuthorsCreator)

	if err != nil {
		return err
	}

	*o = AuthorsCreator(varAuthorsCreator)

	return err
}

type NullableAuthorsCreator struct {
	value *AuthorsCreator
	isSet bool
}

func (v NullableAuthorsCreator) Get() *AuthorsCreator {
	return v.value
}

func (v *NullableAuthorsCreator) Set(val *AuthorsCreator) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthorsCreator) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthorsCreator) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthorsCreator(val *AuthorsCreator) *NullableAuthorsCreator {
	return &NullableAuthorsCreator{value: val, isSet: true}
}

func (v NullableAuthorsCreator) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthorsCreator) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


