/*
Figshare API

Figshare apiv2. Using Swagger 2.0

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package go_figshare

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Timeline type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Timeline{}

// Timeline struct for Timeline
type Timeline struct {
	// Posted date
	Posted NullableString `json:"posted"`
	// Submission date in curation (if curated)
	Submission NullableString `json:"submission"`
	// Revision date from curation (if curated)
	Revision NullableString `json:"revision"`
	// Online posted date
	FirstOnline *string `json:"firstOnline,omitempty"`
	// Publish date
	PublisherPublication *string `json:"publisherPublication,omitempty"`
	// Date when the item was accepted for publication
	PublisherAcceptance *string `json:"publisherAcceptance,omitempty"`
}

type _Timeline Timeline

// NewTimeline instantiates a new Timeline object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTimeline(posted NullableString, submission NullableString, revision NullableString) *Timeline {
	this := Timeline{}
	return &this
}

// NewTimelineWithDefaults instantiates a new Timeline object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTimelineWithDefaults() *Timeline {
	this := Timeline{}
	return &this
}

// GetPosted returns the Posted field value
// If the value is explicit nil, the zero value for string will be returned
func (o *Timeline) GetPosted() string {
	if o == nil || o.Posted.Get() == nil {
		var ret string
		return ret
	}

	return *o.Posted.Get()
}

// GetPostedOk returns a tuple with the Posted field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Timeline) GetPostedOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Posted.Get(), o.Posted.IsSet()
}

// SetPosted sets field value
func (o *Timeline) SetPosted(v string) {
	o.Posted.Set(&v)
}

// GetSubmission returns the Submission field value
// If the value is explicit nil, the zero value for string will be returned
func (o *Timeline) GetSubmission() string {
	if o == nil || o.Submission.Get() == nil {
		var ret string
		return ret
	}

	return *o.Submission.Get()
}

// GetSubmissionOk returns a tuple with the Submission field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Timeline) GetSubmissionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Submission.Get(), o.Submission.IsSet()
}

// SetSubmission sets field value
func (o *Timeline) SetSubmission(v string) {
	o.Submission.Set(&v)
}

// GetRevision returns the Revision field value
// If the value is explicit nil, the zero value for string will be returned
func (o *Timeline) GetRevision() string {
	if o == nil || o.Revision.Get() == nil {
		var ret string
		return ret
	}

	return *o.Revision.Get()
}

// GetRevisionOk returns a tuple with the Revision field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Timeline) GetRevisionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Revision.Get(), o.Revision.IsSet()
}

// SetRevision sets field value
func (o *Timeline) SetRevision(v string) {
	o.Revision.Set(&v)
}

// GetFirstOnline returns the FirstOnline field value if set, zero value otherwise.
func (o *Timeline) GetFirstOnline() string {
	if o == nil || IsNil(o.FirstOnline) {
		var ret string
		return ret
	}
	return *o.FirstOnline
}

// GetFirstOnlineOk returns a tuple with the FirstOnline field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Timeline) GetFirstOnlineOk() (*string, bool) {
	if o == nil || IsNil(o.FirstOnline) {
		return nil, false
	}
	return o.FirstOnline, true
}

// HasFirstOnline returns a boolean if a field has been set.
func (o *Timeline) HasFirstOnline() bool {
	if o != nil && !IsNil(o.FirstOnline) {
		return true
	}

	return false
}

// SetFirstOnline gets a reference to the given string and assigns it to the FirstOnline field.
func (o *Timeline) SetFirstOnline(v string) {
	o.FirstOnline = &v
}

// GetPublisherPublication returns the PublisherPublication field value if set, zero value otherwise.
func (o *Timeline) GetPublisherPublication() string {
	if o == nil || IsNil(o.PublisherPublication) {
		var ret string
		return ret
	}
	return *o.PublisherPublication
}

// GetPublisherPublicationOk returns a tuple with the PublisherPublication field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Timeline) GetPublisherPublicationOk() (*string, bool) {
	if o == nil || IsNil(o.PublisherPublication) {
		return nil, false
	}
	return o.PublisherPublication, true
}

// HasPublisherPublication returns a boolean if a field has been set.
func (o *Timeline) HasPublisherPublication() bool {
	if o != nil && !IsNil(o.PublisherPublication) {
		return true
	}

	return false
}

// SetPublisherPublication gets a reference to the given string and assigns it to the PublisherPublication field.
func (o *Timeline) SetPublisherPublication(v string) {
	o.PublisherPublication = &v
}

// GetPublisherAcceptance returns the PublisherAcceptance field value if set, zero value otherwise.
func (o *Timeline) GetPublisherAcceptance() string {
	if o == nil || IsNil(o.PublisherAcceptance) {
		var ret string
		return ret
	}
	return *o.PublisherAcceptance
}

// GetPublisherAcceptanceOk returns a tuple with the PublisherAcceptance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Timeline) GetPublisherAcceptanceOk() (*string, bool) {
	if o == nil || IsNil(o.PublisherAcceptance) {
		return nil, false
	}
	return o.PublisherAcceptance, true
}

// HasPublisherAcceptance returns a boolean if a field has been set.
func (o *Timeline) HasPublisherAcceptance() bool {
	if o != nil && !IsNil(o.PublisherAcceptance) {
		return true
	}

	return false
}

// SetPublisherAcceptance gets a reference to the given string and assigns it to the PublisherAcceptance field.
func (o *Timeline) SetPublisherAcceptance(v string) {
	o.PublisherAcceptance = &v
}

func (o Timeline) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Timeline) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["posted"] = o.Posted.Get()
	toSerialize["submission"] = o.Submission.Get()
	toSerialize["revision"] = o.Revision.Get()
	if !IsNil(o.FirstOnline) {
		toSerialize["firstOnline"] = o.FirstOnline
	}
	if !IsNil(o.PublisherPublication) {
		toSerialize["publisherPublication"] = o.PublisherPublication
	}
	if !IsNil(o.PublisherAcceptance) {
		toSerialize["publisherAcceptance"] = o.PublisherAcceptance
	}
	return toSerialize, nil
}

func (o *Timeline) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"posted",
		"submission",
		"revision",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTimeline := _Timeline{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTimeline)

	if err != nil {
		return err
	}

	*o = Timeline(varTimeline)

	return err
}

type NullableTimeline struct {
	value *Timeline
	isSet bool
}

func (v NullableTimeline) Get() *Timeline {
	return v.value
}

func (v *NullableTimeline) Set(val *Timeline) {
	v.value = val
	v.isSet = true
}

func (v NullableTimeline) IsSet() bool {
	return v.isSet
}

func (v *NullableTimeline) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTimeline(val *Timeline) *NullableTimeline {
	return &NullableTimeline{value: val, isSet: true}
}

func (v NullableTimeline) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTimeline) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


