/*
Figshare API

Figshare apiv2. Using Swagger 2.0

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package go_figshare

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CurationDetail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CurationDetail{}

// CurationDetail struct for CurationDetail
type CurationDetail struct {
	Item ArticleComplete `json:"item"`
	// The review id
	Id int64 `json:"id"`
	// The group in which the article is present.
	GroupId int64 `json:"group_id"`
	// The ID of the account of the owner of the article of this review.
	AccountId int64 `json:"account_id"`
	// The ID of the account to which this review is assigned.
	AssignedTo int64 `json:"assigned_to"`
	// The ID of the article of this review.
	ArticleId int64 `json:"article_id"`
	// The Version number of the article in review.
	Version int64 `json:"version"`
	// The number of comments in the review.
	CommentsCount int64 `json:"comments_count"`
	// The status of the review.
	Status string `json:"status"`
	// The creation date of the review.
	CreatedDate string `json:"created_date"`
	// The date the review has been modified.
	ModifiedDate string `json:"modified_date"`
	// The last time a comment has been added to the review.
	ReviewDate NullableString `json:"review_date"`
	// The request number of the review.
	RequestNumber int64 `json:"request_number"`
	// The resolution comment of the review.
	ResolutionComment string `json:"resolution_comment"`
}

type _CurationDetail CurationDetail

// NewCurationDetail instantiates a new CurationDetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCurationDetail(item ArticleComplete, id int64, groupId int64, accountId int64, assignedTo int64, articleId int64, version int64, commentsCount int64, status string, createdDate string, modifiedDate string, reviewDate NullableString, requestNumber int64, resolutionComment string) *CurationDetail {
	this := CurationDetail{}
	this.Id = id
	this.GroupId = groupId
	this.AccountId = accountId
	this.AssignedTo = assignedTo
	this.ArticleId = articleId
	this.Version = version
	this.CommentsCount = commentsCount
	this.Status = status
	this.CreatedDate = createdDate
	this.ModifiedDate = modifiedDate
	this.ReviewDate = reviewDate
	this.RequestNumber = requestNumber
	this.ResolutionComment = resolutionComment
	return &this
}

// NewCurationDetailWithDefaults instantiates a new CurationDetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCurationDetailWithDefaults() *CurationDetail {
	this := CurationDetail{}
	return &this
}

// GetItem returns the Item field value
func (o *CurationDetail) GetItem() ArticleComplete {
	if o == nil {
		var ret ArticleComplete
		return ret
	}

	return o.Item
}

// GetItemOk returns a tuple with the Item field value
// and a boolean to check if the value has been set.
func (o *CurationDetail) GetItemOk() (*ArticleComplete, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Item, true
}

// SetItem sets field value
func (o *CurationDetail) SetItem(v ArticleComplete) {
	o.Item = v
}

// GetId returns the Id field value
func (o *CurationDetail) GetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CurationDetail) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CurationDetail) SetId(v int64) {
	o.Id = v
}

// GetGroupId returns the GroupId field value
func (o *CurationDetail) GetGroupId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.GroupId
}

// GetGroupIdOk returns a tuple with the GroupId field value
// and a boolean to check if the value has been set.
func (o *CurationDetail) GetGroupIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GroupId, true
}

// SetGroupId sets field value
func (o *CurationDetail) SetGroupId(v int64) {
	o.GroupId = v
}

// GetAccountId returns the AccountId field value
func (o *CurationDetail) GetAccountId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *CurationDetail) GetAccountIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *CurationDetail) SetAccountId(v int64) {
	o.AccountId = v
}

// GetAssignedTo returns the AssignedTo field value
func (o *CurationDetail) GetAssignedTo() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.AssignedTo
}

// GetAssignedToOk returns a tuple with the AssignedTo field value
// and a boolean to check if the value has been set.
func (o *CurationDetail) GetAssignedToOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AssignedTo, true
}

// SetAssignedTo sets field value
func (o *CurationDetail) SetAssignedTo(v int64) {
	o.AssignedTo = v
}

// GetArticleId returns the ArticleId field value
func (o *CurationDetail) GetArticleId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ArticleId
}

// GetArticleIdOk returns a tuple with the ArticleId field value
// and a boolean to check if the value has been set.
func (o *CurationDetail) GetArticleIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ArticleId, true
}

// SetArticleId sets field value
func (o *CurationDetail) SetArticleId(v int64) {
	o.ArticleId = v
}

// GetVersion returns the Version field value
func (o *CurationDetail) GetVersion() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *CurationDetail) GetVersionOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *CurationDetail) SetVersion(v int64) {
	o.Version = v
}

// GetCommentsCount returns the CommentsCount field value
func (o *CurationDetail) GetCommentsCount() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.CommentsCount
}

// GetCommentsCountOk returns a tuple with the CommentsCount field value
// and a boolean to check if the value has been set.
func (o *CurationDetail) GetCommentsCountOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CommentsCount, true
}

// SetCommentsCount sets field value
func (o *CurationDetail) SetCommentsCount(v int64) {
	o.CommentsCount = v
}

// GetStatus returns the Status field value
func (o *CurationDetail) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *CurationDetail) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *CurationDetail) SetStatus(v string) {
	o.Status = v
}

// GetCreatedDate returns the CreatedDate field value
func (o *CurationDetail) GetCreatedDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedDate
}

// GetCreatedDateOk returns a tuple with the CreatedDate field value
// and a boolean to check if the value has been set.
func (o *CurationDetail) GetCreatedDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedDate, true
}

// SetCreatedDate sets field value
func (o *CurationDetail) SetCreatedDate(v string) {
	o.CreatedDate = v
}

// GetModifiedDate returns the ModifiedDate field value
func (o *CurationDetail) GetModifiedDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ModifiedDate
}

// GetModifiedDateOk returns a tuple with the ModifiedDate field value
// and a boolean to check if the value has been set.
func (o *CurationDetail) GetModifiedDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ModifiedDate, true
}

// SetModifiedDate sets field value
func (o *CurationDetail) SetModifiedDate(v string) {
	o.ModifiedDate = v
}

// GetReviewDate returns the ReviewDate field value
// If the value is explicit nil, the zero value for string will be returned
func (o *CurationDetail) GetReviewDate() string {
	if o == nil || o.ReviewDate.Get() == nil {
		var ret string
		return ret
	}

	return *o.ReviewDate.Get()
}

// GetReviewDateOk returns a tuple with the ReviewDate field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CurationDetail) GetReviewDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReviewDate.Get(), o.ReviewDate.IsSet()
}

// SetReviewDate sets field value
func (o *CurationDetail) SetReviewDate(v string) {
	o.ReviewDate.Set(&v)
}

// GetRequestNumber returns the RequestNumber field value
func (o *CurationDetail) GetRequestNumber() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.RequestNumber
}

// GetRequestNumberOk returns a tuple with the RequestNumber field value
// and a boolean to check if the value has been set.
func (o *CurationDetail) GetRequestNumberOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestNumber, true
}

// SetRequestNumber sets field value
func (o *CurationDetail) SetRequestNumber(v int64) {
	o.RequestNumber = v
}

// GetResolutionComment returns the ResolutionComment field value
func (o *CurationDetail) GetResolutionComment() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResolutionComment
}

// GetResolutionCommentOk returns a tuple with the ResolutionComment field value
// and a boolean to check if the value has been set.
func (o *CurationDetail) GetResolutionCommentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResolutionComment, true
}

// SetResolutionComment sets field value
func (o *CurationDetail) SetResolutionComment(v string) {
	o.ResolutionComment = v
}

func (o CurationDetail) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CurationDetail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["item"] = o.Item
	toSerialize["id"] = o.Id
	toSerialize["group_id"] = o.GroupId
	toSerialize["account_id"] = o.AccountId
	toSerialize["assigned_to"] = o.AssignedTo
	toSerialize["article_id"] = o.ArticleId
	toSerialize["version"] = o.Version
	toSerialize["comments_count"] = o.CommentsCount
	toSerialize["status"] = o.Status
	toSerialize["created_date"] = o.CreatedDate
	toSerialize["modified_date"] = o.ModifiedDate
	toSerialize["review_date"] = o.ReviewDate.Get()
	toSerialize["request_number"] = o.RequestNumber
	toSerialize["resolution_comment"] = o.ResolutionComment
	return toSerialize, nil
}

func (o *CurationDetail) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"item",
		"id",
		"group_id",
		"account_id",
		"assigned_to",
		"article_id",
		"version",
		"comments_count",
		"status",
		"created_date",
		"modified_date",
		"review_date",
		"request_number",
		"resolution_comment",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCurationDetail := _CurationDetail{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCurationDetail)

	if err != nil {
		return err
	}

	*o = CurationDetail(varCurationDetail)

	return err
}

type NullableCurationDetail struct {
	value *CurationDetail
	isSet bool
}

func (v NullableCurationDetail) Get() *CurationDetail {
	return v.value
}

func (v *NullableCurationDetail) Set(val *CurationDetail) {
	v.value = val
	v.isSet = true
}

func (v NullableCurationDetail) IsSet() bool {
	return v.isSet
}

func (v *NullableCurationDetail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCurationDetail(val *CurationDetail) *NullableCurationDetail {
	return &NullableCurationDetail{value: val, isSet: true}
}

func (v NullableCurationDetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCurationDetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


