/*
Figshare API

Figshare apiv2. Using Swagger 2.0

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package figshare

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ProjectCollaborator type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectCollaborator{}

// ProjectCollaborator struct for ProjectCollaborator
type ProjectCollaborator struct {
	// Collaborator name
	Name string `json:"name"`
	// Collaborator role
	RoleName string `json:"role_name"`
	// Status of collaborator invitation
	Status string `json:"status"`
	// Collaborator id
	UserId int32 `json:"user_id"`
}

type _ProjectCollaborator ProjectCollaborator

// NewProjectCollaborator instantiates a new ProjectCollaborator object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectCollaborator(name string, roleName string, status string, userId int32) *ProjectCollaborator {
	this := ProjectCollaborator{}
	this.Name = name
	this.RoleName = roleName
	this.Status = status
	this.UserId = userId
	return &this
}

// NewProjectCollaboratorWithDefaults instantiates a new ProjectCollaborator object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectCollaboratorWithDefaults() *ProjectCollaborator {
	this := ProjectCollaborator{}
	return &this
}

// GetName returns the Name field value
func (o *ProjectCollaborator) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ProjectCollaborator) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ProjectCollaborator) SetName(v string) {
	o.Name = v
}

// GetRoleName returns the RoleName field value
func (o *ProjectCollaborator) GetRoleName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RoleName
}

// GetRoleNameOk returns a tuple with the RoleName field value
// and a boolean to check if the value has been set.
func (o *ProjectCollaborator) GetRoleNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RoleName, true
}

// SetRoleName sets field value
func (o *ProjectCollaborator) SetRoleName(v string) {
	o.RoleName = v
}

// GetStatus returns the Status field value
func (o *ProjectCollaborator) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ProjectCollaborator) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ProjectCollaborator) SetStatus(v string) {
	o.Status = v
}

// GetUserId returns the UserId field value
func (o *ProjectCollaborator) GetUserId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *ProjectCollaborator) GetUserIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *ProjectCollaborator) SetUserId(v int32) {
	o.UserId = v
}

func (o ProjectCollaborator) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectCollaborator) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["role_name"] = o.RoleName
	toSerialize["status"] = o.Status
	toSerialize["user_id"] = o.UserId
	return toSerialize, nil
}

func (o *ProjectCollaborator) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"role_name",
		"status",
		"user_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProjectCollaborator := _ProjectCollaborator{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProjectCollaborator)

	if err != nil {
		return err
	}

	*o = ProjectCollaborator(varProjectCollaborator)

	return err
}

type NullableProjectCollaborator struct {
	value *ProjectCollaborator
	isSet bool
}

func (v NullableProjectCollaborator) Get() *ProjectCollaborator {
	return v.value
}

func (v *NullableProjectCollaborator) Set(val *ProjectCollaborator) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectCollaborator) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectCollaborator) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectCollaborator(val *ProjectCollaborator) *NullableProjectCollaborator {
	return &NullableProjectCollaborator{value: val, isSet: true}
}

func (v NullableProjectCollaborator) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectCollaborator) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


