/*
Figshare API

Figshare apiv2. Using Swagger 2.0

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package go_figshare

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Account type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Account{}

// Account struct for Account
type Account struct {
	// Account id
	Id int64 `json:"id"`
	// First Name
	FirstName string `json:"first_name"`
	// Last Name
	LastName string `json:"last_name"`
	// Account used private quota
	UsedQuotaPrivate int64 `json:"used_quota_private"`
	// Date of last account modification
	ModifiedDate string `json:"modified_date"`
	// Account total used quota
	UsedQuota int64 `json:"used_quota"`
	// Date when account was created
	CreatedDate string `json:"created_date"`
	// Account quota
	Quota int64 `json:"quota"`
	// Account group id
	GroupId int64 `json:"group_id"`
	// Account institution user id
	InstitutionUserId string `json:"institution_user_id"`
	// Account institution
	InstitutionId int64 `json:"institution_id"`
	// User email
	Email string `json:"email"`
	// Account public used quota
	UsedQuotaPublic int64 `json:"used_quota_public"`
	// True if a quota request is pending
	PendingQuotaRequest bool `json:"pending_quota_request"`
	// Account activity status
	Active int64 `json:"active"`
	// Maximum upload size for account
	MaximumFileSize int64 `json:"maximum_file_size"`
	// User id associated with account, useful for example for adding the account as an author to an item
	UserId int64 `json:"user_id"`
	// ORCID iD associated to account
	OrcidId string `json:"orcid_id"`
	// Symplectic ID associated to account
	SymplecticUserId string `json:"symplectic_user_id"`
}

type _Account Account

// NewAccount instantiates a new Account object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccount(id int64, firstName string, lastName string, usedQuotaPrivate int64, modifiedDate string, usedQuota int64, createdDate string, quota int64, groupId int64, institutionUserId string, institutionId int64, email string, usedQuotaPublic int64, pendingQuotaRequest bool, active int64, maximumFileSize int64, userId int64, orcidId string, symplecticUserId string) *Account {
	this := Account{}
	this.Id = id
	this.FirstName = firstName
	this.LastName = lastName
	this.UsedQuotaPrivate = usedQuotaPrivate
	this.ModifiedDate = modifiedDate
	this.UsedQuota = usedQuota
	this.CreatedDate = createdDate
	this.Quota = quota
	this.GroupId = groupId
	this.InstitutionUserId = institutionUserId
	this.InstitutionId = institutionId
	this.Email = email
	this.UsedQuotaPublic = usedQuotaPublic
	this.PendingQuotaRequest = pendingQuotaRequest
	this.Active = active
	this.MaximumFileSize = maximumFileSize
	this.UserId = userId
	this.OrcidId = orcidId
	this.SymplecticUserId = symplecticUserId
	return &this
}

// NewAccountWithDefaults instantiates a new Account object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountWithDefaults() *Account {
	this := Account{}
	return &this
}

// GetId returns the Id field value
func (o *Account) GetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Account) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Account) SetId(v int64) {
	o.Id = v
}

// GetFirstName returns the FirstName field value
func (o *Account) GetFirstName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value
// and a boolean to check if the value has been set.
func (o *Account) GetFirstNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FirstName, true
}

// SetFirstName sets field value
func (o *Account) SetFirstName(v string) {
	o.FirstName = v
}

// GetLastName returns the LastName field value
func (o *Account) GetLastName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value
// and a boolean to check if the value has been set.
func (o *Account) GetLastNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastName, true
}

// SetLastName sets field value
func (o *Account) SetLastName(v string) {
	o.LastName = v
}

// GetUsedQuotaPrivate returns the UsedQuotaPrivate field value
func (o *Account) GetUsedQuotaPrivate() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.UsedQuotaPrivate
}

// GetUsedQuotaPrivateOk returns a tuple with the UsedQuotaPrivate field value
// and a boolean to check if the value has been set.
func (o *Account) GetUsedQuotaPrivateOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UsedQuotaPrivate, true
}

// SetUsedQuotaPrivate sets field value
func (o *Account) SetUsedQuotaPrivate(v int64) {
	o.UsedQuotaPrivate = v
}

// GetModifiedDate returns the ModifiedDate field value
func (o *Account) GetModifiedDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ModifiedDate
}

// GetModifiedDateOk returns a tuple with the ModifiedDate field value
// and a boolean to check if the value has been set.
func (o *Account) GetModifiedDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ModifiedDate, true
}

// SetModifiedDate sets field value
func (o *Account) SetModifiedDate(v string) {
	o.ModifiedDate = v
}

// GetUsedQuota returns the UsedQuota field value
func (o *Account) GetUsedQuota() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.UsedQuota
}

// GetUsedQuotaOk returns a tuple with the UsedQuota field value
// and a boolean to check if the value has been set.
func (o *Account) GetUsedQuotaOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UsedQuota, true
}

// SetUsedQuota sets field value
func (o *Account) SetUsedQuota(v int64) {
	o.UsedQuota = v
}

// GetCreatedDate returns the CreatedDate field value
func (o *Account) GetCreatedDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedDate
}

// GetCreatedDateOk returns a tuple with the CreatedDate field value
// and a boolean to check if the value has been set.
func (o *Account) GetCreatedDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedDate, true
}

// SetCreatedDate sets field value
func (o *Account) SetCreatedDate(v string) {
	o.CreatedDate = v
}

// GetQuota returns the Quota field value
func (o *Account) GetQuota() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Quota
}

// GetQuotaOk returns a tuple with the Quota field value
// and a boolean to check if the value has been set.
func (o *Account) GetQuotaOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Quota, true
}

// SetQuota sets field value
func (o *Account) SetQuota(v int64) {
	o.Quota = v
}

// GetGroupId returns the GroupId field value
func (o *Account) GetGroupId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.GroupId
}

// GetGroupIdOk returns a tuple with the GroupId field value
// and a boolean to check if the value has been set.
func (o *Account) GetGroupIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GroupId, true
}

// SetGroupId sets field value
func (o *Account) SetGroupId(v int64) {
	o.GroupId = v
}

// GetInstitutionUserId returns the InstitutionUserId field value
func (o *Account) GetInstitutionUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.InstitutionUserId
}

// GetInstitutionUserIdOk returns a tuple with the InstitutionUserId field value
// and a boolean to check if the value has been set.
func (o *Account) GetInstitutionUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InstitutionUserId, true
}

// SetInstitutionUserId sets field value
func (o *Account) SetInstitutionUserId(v string) {
	o.InstitutionUserId = v
}

// GetInstitutionId returns the InstitutionId field value
func (o *Account) GetInstitutionId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.InstitutionId
}

// GetInstitutionIdOk returns a tuple with the InstitutionId field value
// and a boolean to check if the value has been set.
func (o *Account) GetInstitutionIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InstitutionId, true
}

// SetInstitutionId sets field value
func (o *Account) SetInstitutionId(v int64) {
	o.InstitutionId = v
}

// GetEmail returns the Email field value
func (o *Account) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *Account) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *Account) SetEmail(v string) {
	o.Email = v
}

// GetUsedQuotaPublic returns the UsedQuotaPublic field value
func (o *Account) GetUsedQuotaPublic() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.UsedQuotaPublic
}

// GetUsedQuotaPublicOk returns a tuple with the UsedQuotaPublic field value
// and a boolean to check if the value has been set.
func (o *Account) GetUsedQuotaPublicOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UsedQuotaPublic, true
}

// SetUsedQuotaPublic sets field value
func (o *Account) SetUsedQuotaPublic(v int64) {
	o.UsedQuotaPublic = v
}

// GetPendingQuotaRequest returns the PendingQuotaRequest field value
func (o *Account) GetPendingQuotaRequest() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.PendingQuotaRequest
}

// GetPendingQuotaRequestOk returns a tuple with the PendingQuotaRequest field value
// and a boolean to check if the value has been set.
func (o *Account) GetPendingQuotaRequestOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PendingQuotaRequest, true
}

// SetPendingQuotaRequest sets field value
func (o *Account) SetPendingQuotaRequest(v bool) {
	o.PendingQuotaRequest = v
}

// GetActive returns the Active field value
func (o *Account) GetActive() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Active
}

// GetActiveOk returns a tuple with the Active field value
// and a boolean to check if the value has been set.
func (o *Account) GetActiveOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Active, true
}

// SetActive sets field value
func (o *Account) SetActive(v int64) {
	o.Active = v
}

// GetMaximumFileSize returns the MaximumFileSize field value
func (o *Account) GetMaximumFileSize() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.MaximumFileSize
}

// GetMaximumFileSizeOk returns a tuple with the MaximumFileSize field value
// and a boolean to check if the value has been set.
func (o *Account) GetMaximumFileSizeOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaximumFileSize, true
}

// SetMaximumFileSize sets field value
func (o *Account) SetMaximumFileSize(v int64) {
	o.MaximumFileSize = v
}

// GetUserId returns the UserId field value
func (o *Account) GetUserId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *Account) GetUserIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *Account) SetUserId(v int64) {
	o.UserId = v
}

// GetOrcidId returns the OrcidId field value
func (o *Account) GetOrcidId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrcidId
}

// GetOrcidIdOk returns a tuple with the OrcidId field value
// and a boolean to check if the value has been set.
func (o *Account) GetOrcidIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrcidId, true
}

// SetOrcidId sets field value
func (o *Account) SetOrcidId(v string) {
	o.OrcidId = v
}

// GetSymplecticUserId returns the SymplecticUserId field value
func (o *Account) GetSymplecticUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SymplecticUserId
}

// GetSymplecticUserIdOk returns a tuple with the SymplecticUserId field value
// and a boolean to check if the value has been set.
func (o *Account) GetSymplecticUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SymplecticUserId, true
}

// SetSymplecticUserId sets field value
func (o *Account) SetSymplecticUserId(v string) {
	o.SymplecticUserId = v
}

func (o Account) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Account) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["first_name"] = o.FirstName
	toSerialize["last_name"] = o.LastName
	toSerialize["used_quota_private"] = o.UsedQuotaPrivate
	toSerialize["modified_date"] = o.ModifiedDate
	toSerialize["used_quota"] = o.UsedQuota
	toSerialize["created_date"] = o.CreatedDate
	toSerialize["quota"] = o.Quota
	toSerialize["group_id"] = o.GroupId
	toSerialize["institution_user_id"] = o.InstitutionUserId
	toSerialize["institution_id"] = o.InstitutionId
	toSerialize["email"] = o.Email
	toSerialize["used_quota_public"] = o.UsedQuotaPublic
	toSerialize["pending_quota_request"] = o.PendingQuotaRequest
	toSerialize["active"] = o.Active
	toSerialize["maximum_file_size"] = o.MaximumFileSize
	toSerialize["user_id"] = o.UserId
	toSerialize["orcid_id"] = o.OrcidId
	toSerialize["symplectic_user_id"] = o.SymplecticUserId
	return toSerialize, nil
}

func (o *Account) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"first_name",
		"last_name",
		"used_quota_private",
		"modified_date",
		"used_quota",
		"created_date",
		"quota",
		"group_id",
		"institution_user_id",
		"institution_id",
		"email",
		"used_quota_public",
		"pending_quota_request",
		"active",
		"maximum_file_size",
		"user_id",
		"orcid_id",
		"symplectic_user_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAccount := _Account{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAccount)

	if err != nil {
		return err
	}

	*o = Account(varAccount)

	return err
}

type NullableAccount struct {
	value *Account
	isSet bool
}

func (v NullableAccount) Get() *Account {
	return v.value
}

func (v *NullableAccount) Set(val *Account) {
	v.value = val
	v.isSet = true
}

func (v NullableAccount) IsSet() bool {
	return v.isSet
}

func (v *NullableAccount) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccount(val *Account) *NullableAccount {
	return &NullableAccount{value: val, isSet: true}
}

func (v NullableAccount) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccount) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


