/*
Figshare API

Figshare apiv2. Using Swagger 2.0

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package figshare

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CollectionDOI type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CollectionDOI{}

// CollectionDOI struct for CollectionDOI
type CollectionDOI struct {
	// Reserved DOI
	Doi string `json:"doi"`
}

type _CollectionDOI CollectionDOI

// NewCollectionDOI instantiates a new CollectionDOI object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCollectionDOI(doi string) *CollectionDOI {
	this := CollectionDOI{}
	this.Doi = doi
	return &this
}

// NewCollectionDOIWithDefaults instantiates a new CollectionDOI object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCollectionDOIWithDefaults() *CollectionDOI {
	this := CollectionDOI{}
	return &this
}

// GetDoi returns the Doi field value
func (o *CollectionDOI) GetDoi() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Doi
}

// GetDoiOk returns a tuple with the Doi field value
// and a boolean to check if the value has been set.
func (o *CollectionDOI) GetDoiOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Doi, true
}

// SetDoi sets field value
func (o *CollectionDOI) SetDoi(v string) {
	o.Doi = v
}

func (o CollectionDOI) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CollectionDOI) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["doi"] = o.Doi
	return toSerialize, nil
}

func (o *CollectionDOI) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"doi",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCollectionDOI := _CollectionDOI{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCollectionDOI)

	if err != nil {
		return err
	}

	*o = CollectionDOI(varCollectionDOI)

	return err
}

type NullableCollectionDOI struct {
	value *CollectionDOI
	isSet bool
}

func (v NullableCollectionDOI) Get() *CollectionDOI {
	return v.value
}

func (v *NullableCollectionDOI) Set(val *CollectionDOI) {
	v.value = val
	v.isSet = true
}

func (v NullableCollectionDOI) IsSet() bool {
	return v.isSet
}

func (v *NullableCollectionDOI) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCollectionDOI(val *CollectionDOI) *NullableCollectionDOI {
	return &NullableCollectionDOI{value: val, isSet: true}
}

func (v NullableCollectionDOI) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCollectionDOI) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


