/*
Figshare API

Figshare apiv2. Using Swagger 2.0

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package figshare

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ShortAccount type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ShortAccount{}

// ShortAccount struct for ShortAccount
type ShortAccount struct {
	// Account activity status
	Active int64 `json:"active"`
	// User email
	Email string `json:"email"`
	// First Name
	FirstName string `json:"first_name"`
	// Account id
	Id int64 `json:"id"`
	// Account institution
	InstitutionId int64 `json:"institution_id"`
	// Account institution user id
	InstitutionUserId string `json:"institution_user_id"`
	// Last Name
	LastName string `json:"last_name"`
	// ORCID iD associated to account
	OrcidId string `json:"orcid_id"`
	// Total storage available to account, in bytes
	Quota int64 `json:"quota"`
	// Symplectic ID associated to account
	SymplecticUserId string `json:"symplectic_user_id"`
	// Storage used by the account, in bytes
	UsedQuota int64 `json:"used_quota"`
	// User id associated with account, useful for example for adding the account as an author to an item
	UserId int64 `json:"user_id"`
}

type _ShortAccount ShortAccount

// NewShortAccount instantiates a new ShortAccount object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewShortAccount(active int64, email string, firstName string, id int64, institutionId int64, institutionUserId string, lastName string, orcidId string, quota int64, symplecticUserId string, usedQuota int64, userId int64) *ShortAccount {
	this := ShortAccount{}
	this.Active = active
	this.Email = email
	this.FirstName = firstName
	this.Id = id
	this.InstitutionId = institutionId
	this.InstitutionUserId = institutionUserId
	this.LastName = lastName
	this.OrcidId = orcidId
	this.Quota = quota
	this.SymplecticUserId = symplecticUserId
	this.UsedQuota = usedQuota
	this.UserId = userId
	return &this
}

// NewShortAccountWithDefaults instantiates a new ShortAccount object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewShortAccountWithDefaults() *ShortAccount {
	this := ShortAccount{}
	return &this
}

// GetActive returns the Active field value
func (o *ShortAccount) GetActive() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Active
}

// GetActiveOk returns a tuple with the Active field value
// and a boolean to check if the value has been set.
func (o *ShortAccount) GetActiveOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Active, true
}

// SetActive sets field value
func (o *ShortAccount) SetActive(v int64) {
	o.Active = v
}

// GetEmail returns the Email field value
func (o *ShortAccount) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *ShortAccount) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *ShortAccount) SetEmail(v string) {
	o.Email = v
}

// GetFirstName returns the FirstName field value
func (o *ShortAccount) GetFirstName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value
// and a boolean to check if the value has been set.
func (o *ShortAccount) GetFirstNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FirstName, true
}

// SetFirstName sets field value
func (o *ShortAccount) SetFirstName(v string) {
	o.FirstName = v
}

// GetId returns the Id field value
func (o *ShortAccount) GetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ShortAccount) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ShortAccount) SetId(v int64) {
	o.Id = v
}

// GetInstitutionId returns the InstitutionId field value
func (o *ShortAccount) GetInstitutionId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.InstitutionId
}

// GetInstitutionIdOk returns a tuple with the InstitutionId field value
// and a boolean to check if the value has been set.
func (o *ShortAccount) GetInstitutionIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InstitutionId, true
}

// SetInstitutionId sets field value
func (o *ShortAccount) SetInstitutionId(v int64) {
	o.InstitutionId = v
}

// GetInstitutionUserId returns the InstitutionUserId field value
func (o *ShortAccount) GetInstitutionUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.InstitutionUserId
}

// GetInstitutionUserIdOk returns a tuple with the InstitutionUserId field value
// and a boolean to check if the value has been set.
func (o *ShortAccount) GetInstitutionUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InstitutionUserId, true
}

// SetInstitutionUserId sets field value
func (o *ShortAccount) SetInstitutionUserId(v string) {
	o.InstitutionUserId = v
}

// GetLastName returns the LastName field value
func (o *ShortAccount) GetLastName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value
// and a boolean to check if the value has been set.
func (o *ShortAccount) GetLastNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastName, true
}

// SetLastName sets field value
func (o *ShortAccount) SetLastName(v string) {
	o.LastName = v
}

// GetOrcidId returns the OrcidId field value
func (o *ShortAccount) GetOrcidId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrcidId
}

// GetOrcidIdOk returns a tuple with the OrcidId field value
// and a boolean to check if the value has been set.
func (o *ShortAccount) GetOrcidIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrcidId, true
}

// SetOrcidId sets field value
func (o *ShortAccount) SetOrcidId(v string) {
	o.OrcidId = v
}

// GetQuota returns the Quota field value
func (o *ShortAccount) GetQuota() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Quota
}

// GetQuotaOk returns a tuple with the Quota field value
// and a boolean to check if the value has been set.
func (o *ShortAccount) GetQuotaOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Quota, true
}

// SetQuota sets field value
func (o *ShortAccount) SetQuota(v int64) {
	o.Quota = v
}

// GetSymplecticUserId returns the SymplecticUserId field value
func (o *ShortAccount) GetSymplecticUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SymplecticUserId
}

// GetSymplecticUserIdOk returns a tuple with the SymplecticUserId field value
// and a boolean to check if the value has been set.
func (o *ShortAccount) GetSymplecticUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SymplecticUserId, true
}

// SetSymplecticUserId sets field value
func (o *ShortAccount) SetSymplecticUserId(v string) {
	o.SymplecticUserId = v
}

// GetUsedQuota returns the UsedQuota field value
func (o *ShortAccount) GetUsedQuota() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.UsedQuota
}

// GetUsedQuotaOk returns a tuple with the UsedQuota field value
// and a boolean to check if the value has been set.
func (o *ShortAccount) GetUsedQuotaOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UsedQuota, true
}

// SetUsedQuota sets field value
func (o *ShortAccount) SetUsedQuota(v int64) {
	o.UsedQuota = v
}

// GetUserId returns the UserId field value
func (o *ShortAccount) GetUserId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *ShortAccount) GetUserIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *ShortAccount) SetUserId(v int64) {
	o.UserId = v
}

func (o ShortAccount) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ShortAccount) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["active"] = o.Active
	toSerialize["email"] = o.Email
	toSerialize["first_name"] = o.FirstName
	toSerialize["id"] = o.Id
	toSerialize["institution_id"] = o.InstitutionId
	toSerialize["institution_user_id"] = o.InstitutionUserId
	toSerialize["last_name"] = o.LastName
	toSerialize["orcid_id"] = o.OrcidId
	toSerialize["quota"] = o.Quota
	toSerialize["symplectic_user_id"] = o.SymplecticUserId
	toSerialize["used_quota"] = o.UsedQuota
	toSerialize["user_id"] = o.UserId
	return toSerialize, nil
}

func (o *ShortAccount) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"active",
		"email",
		"first_name",
		"id",
		"institution_id",
		"institution_user_id",
		"last_name",
		"orcid_id",
		"quota",
		"symplectic_user_id",
		"used_quota",
		"user_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varShortAccount := _ShortAccount{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varShortAccount)

	if err != nil {
		return err
	}

	*o = ShortAccount(varShortAccount)

	return err
}

type NullableShortAccount struct {
	value *ShortAccount
	isSet bool
}

func (v NullableShortAccount) Get() *ShortAccount {
	return v.value
}

func (v *NullableShortAccount) Set(val *ShortAccount) {
	v.value = val
	v.isSet = true
}

func (v NullableShortAccount) IsSet() bool {
	return v.isSet
}

func (v *NullableShortAccount) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableShortAccount(val *ShortAccount) *NullableShortAccount {
	return &NullableShortAccount{value: val, isSet: true}
}

func (v NullableShortAccount) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableShortAccount) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


