/*
Figshare API

Figshare apiv2. Using Swagger 2.0

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package figshare

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Collaborator type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Collaborator{}

// Collaborator struct for Collaborator
type Collaborator struct {
	// Collaborator name
	Name string `json:"name"`
	// Collaborator role
	RoleName string `json:"role_name"`
	// Collaborator id
	UserId int32 `json:"user_id"`
}

type _Collaborator Collaborator

// NewCollaborator instantiates a new Collaborator object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCollaborator(name string, roleName string, userId int32) *Collaborator {
	this := Collaborator{}
	this.Name = name
	this.RoleName = roleName
	this.UserId = userId
	return &this
}

// NewCollaboratorWithDefaults instantiates a new Collaborator object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCollaboratorWithDefaults() *Collaborator {
	this := Collaborator{}
	return &this
}

// GetName returns the Name field value
func (o *Collaborator) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Collaborator) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Collaborator) SetName(v string) {
	o.Name = v
}

// GetRoleName returns the RoleName field value
func (o *Collaborator) GetRoleName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RoleName
}

// GetRoleNameOk returns a tuple with the RoleName field value
// and a boolean to check if the value has been set.
func (o *Collaborator) GetRoleNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RoleName, true
}

// SetRoleName sets field value
func (o *Collaborator) SetRoleName(v string) {
	o.RoleName = v
}

// GetUserId returns the UserId field value
func (o *Collaborator) GetUserId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *Collaborator) GetUserIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *Collaborator) SetUserId(v int32) {
	o.UserId = v
}

func (o Collaborator) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Collaborator) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["role_name"] = o.RoleName
	toSerialize["user_id"] = o.UserId
	return toSerialize, nil
}

func (o *Collaborator) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"role_name",
		"user_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCollaborator := _Collaborator{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCollaborator)

	if err != nil {
		return err
	}

	*o = Collaborator(varCollaborator)

	return err
}

type NullableCollaborator struct {
	value *Collaborator
	isSet bool
}

func (v NullableCollaborator) Get() *Collaborator {
	return v.value
}

func (v *NullableCollaborator) Set(val *Collaborator) {
	v.value = val
	v.isSet = true
}

func (v NullableCollaborator) IsSet() bool {
	return v.isSet
}

func (v *NullableCollaborator) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCollaborator(val *Collaborator) *NullableCollaborator {
	return &NullableCollaborator{value: val, isSet: true}
}

func (v NullableCollaborator) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCollaborator) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


