/*
Figshare API

Figshare apiv2. Using Swagger 2.0

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package go_figshare

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ArticleVersions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ArticleVersions{}

// ArticleVersions struct for ArticleVersions
type ArticleVersions struct {
	// Version number
	Version int64 `json:"version"`
	// Api endpoint for the item version
	Url string `json:"url"`
}

type _ArticleVersions ArticleVersions

// NewArticleVersions instantiates a new ArticleVersions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewArticleVersions(version int64, url string) *ArticleVersions {
	this := ArticleVersions{}
	this.Version = version
	this.Url = url
	return &this
}

// NewArticleVersionsWithDefaults instantiates a new ArticleVersions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewArticleVersionsWithDefaults() *ArticleVersions {
	this := ArticleVersions{}
	return &this
}

// GetVersion returns the Version field value
func (o *ArticleVersions) GetVersion() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *ArticleVersions) GetVersionOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *ArticleVersions) SetVersion(v int64) {
	o.Version = v
}

// GetUrl returns the Url field value
func (o *ArticleVersions) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *ArticleVersions) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *ArticleVersions) SetUrl(v string) {
	o.Url = v
}

func (o ArticleVersions) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ArticleVersions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["version"] = o.Version
	toSerialize["url"] = o.Url
	return toSerialize, nil
}

func (o *ArticleVersions) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"version",
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varArticleVersions := _ArticleVersions{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varArticleVersions)

	if err != nil {
		return err
	}

	*o = ArticleVersions(varArticleVersions)

	return err
}

type NullableArticleVersions struct {
	value *ArticleVersions
	isSet bool
}

func (v NullableArticleVersions) Get() *ArticleVersions {
	return v.value
}

func (v *NullableArticleVersions) Set(val *ArticleVersions) {
	v.value = val
	v.isSet = true
}

func (v NullableArticleVersions) IsSet() bool {
	return v.isSet
}

func (v *NullableArticleVersions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableArticleVersions(val *ArticleVersions) *NullableArticleVersions {
	return &NullableArticleVersions{value: val, isSet: true}
}

func (v NullableArticleVersions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableArticleVersions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


