/*
Figshare API

Figshare apiv2. Using Swagger 2.0

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package go_figshare

import (
	"encoding/json"
)

// checks if the FundingSearch type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FundingSearch{}

// FundingSearch struct for FundingSearch
type FundingSearch struct {
	// Search term
	SearchFor *string `json:"search_for,omitempty"`
}

// NewFundingSearch instantiates a new FundingSearch object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFundingSearch() *FundingSearch {
	this := FundingSearch{}
	return &this
}

// NewFundingSearchWithDefaults instantiates a new FundingSearch object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFundingSearchWithDefaults() *FundingSearch {
	this := FundingSearch{}
	return &this
}

// GetSearchFor returns the SearchFor field value if set, zero value otherwise.
func (o *FundingSearch) GetSearchFor() string {
	if o == nil || IsNil(o.SearchFor) {
		var ret string
		return ret
	}
	return *o.SearchFor
}

// GetSearchForOk returns a tuple with the SearchFor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FundingSearch) GetSearchForOk() (*string, bool) {
	if o == nil || IsNil(o.SearchFor) {
		return nil, false
	}
	return o.SearchFor, true
}

// HasSearchFor returns a boolean if a field has been set.
func (o *FundingSearch) HasSearchFor() bool {
	if o != nil && !IsNil(o.SearchFor) {
		return true
	}

	return false
}

// SetSearchFor gets a reference to the given string and assigns it to the SearchFor field.
func (o *FundingSearch) SetSearchFor(v string) {
	o.SearchFor = &v
}

func (o FundingSearch) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FundingSearch) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SearchFor) {
		toSerialize["search_for"] = o.SearchFor
	}
	return toSerialize, nil
}

type NullableFundingSearch struct {
	value *FundingSearch
	isSet bool
}

func (v NullableFundingSearch) Get() *FundingSearch {
	return v.value
}

func (v *NullableFundingSearch) Set(val *FundingSearch) {
	v.value = val
	v.isSet = true
}

func (v NullableFundingSearch) IsSet() bool {
	return v.isSet
}

func (v *NullableFundingSearch) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFundingSearch(val *FundingSearch) *NullableFundingSearch {
	return &NullableFundingSearch{value: val, isSet: true}
}

func (v NullableFundingSearch) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFundingSearch) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


