/*
Figshare API

Figshare apiv2. Using Swagger 2.0

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package go_figshare

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ProjectCompletePrivate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectCompletePrivate{}

// ProjectCompletePrivate struct for ProjectCompletePrivate
type ProjectCompletePrivate struct {
	// Project funding
	Funding string `json:"funding"`
	// Full Project funding information
	FundingList []FundingInformation `json:"funding_list"`
	// Project description
	Description string `json:"description"`
	// Project public url
	FigshareUrl NullableString `json:"figshare_url"`
	// List of project collaborators
	Collaborators []Collaborator `json:"collaborators"`
	// Project quota
	Quota int64 `json:"quota"`
	// Project used quota
	UsedQuota int64 `json:"used_quota"`
	// Date when project was created
	CreatedDate string `json:"created_date"`
	// Date when project was last modified
	ModifiedDate string `json:"modified_date"`
	// Project private quota used
	UsedQuotaPrivate int64 `json:"used_quota_private"`
	// Project public quota used
	UsedQuotaPublic int64 `json:"used_quota_public"`
	// Group of project if any
	GroupId int64 `json:"group_id"`
	// ID of the account owning the project
	AccountId int64 `json:"account_id"`
	// Collection custom fields
	CustomFields []ShortCustomField `json:"custom_fields"`
	// Role inside this project
	Role string `json:"role"`
	// Project storage type
	Storage string `json:"storage"`
	// Api endpoint
	Url string `json:"url"`
	// Date when project was published
	PublishedDate NullableString `json:"published_date"`
	// Project id
	Id int64 `json:"id"`
	// Project title
	Title string `json:"title"`
}

type _ProjectCompletePrivate ProjectCompletePrivate

// NewProjectCompletePrivate instantiates a new ProjectCompletePrivate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectCompletePrivate(funding string, fundingList []FundingInformation, description string, figshareUrl NullableString, collaborators []Collaborator, quota int64, usedQuota int64, createdDate string, modifiedDate string, usedQuotaPrivate int64, usedQuotaPublic int64, groupId int64, accountId int64, customFields []ShortCustomField, role string, storage string, url string, publishedDate NullableString, id int64, title string) *ProjectCompletePrivate {
	this := ProjectCompletePrivate{}
	this.Role = role
	this.Storage = storage
	this.Url = url
	this.PublishedDate = publishedDate
	this.Id = id
	this.Title = title
	this.CreatedDate = createdDate
	this.ModifiedDate = modifiedDate
	return &this
}

// NewProjectCompletePrivateWithDefaults instantiates a new ProjectCompletePrivate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectCompletePrivateWithDefaults() *ProjectCompletePrivate {
	this := ProjectCompletePrivate{}
	return &this
}

// GetFunding returns the Funding field value
func (o *ProjectCompletePrivate) GetFunding() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Funding
}

// GetFundingOk returns a tuple with the Funding field value
// and a boolean to check if the value has been set.
func (o *ProjectCompletePrivate) GetFundingOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Funding, true
}

// SetFunding sets field value
func (o *ProjectCompletePrivate) SetFunding(v string) {
	o.Funding = v
}

// GetFundingList returns the FundingList field value
func (o *ProjectCompletePrivate) GetFundingList() []FundingInformation {
	if o == nil {
		var ret []FundingInformation
		return ret
	}

	return o.FundingList
}

// GetFundingListOk returns a tuple with the FundingList field value
// and a boolean to check if the value has been set.
func (o *ProjectCompletePrivate) GetFundingListOk() ([]FundingInformation, bool) {
	if o == nil {
		return nil, false
	}
	return o.FundingList, true
}

// SetFundingList sets field value
func (o *ProjectCompletePrivate) SetFundingList(v []FundingInformation) {
	o.FundingList = v
}

// GetDescription returns the Description field value
func (o *ProjectCompletePrivate) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *ProjectCompletePrivate) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *ProjectCompletePrivate) SetDescription(v string) {
	o.Description = v
}

// GetFigshareUrl returns the FigshareUrl field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ProjectCompletePrivate) GetFigshareUrl() string {
	if o == nil || o.FigshareUrl.Get() == nil {
		var ret string
		return ret
	}

	return *o.FigshareUrl.Get()
}

// GetFigshareUrlOk returns a tuple with the FigshareUrl field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProjectCompletePrivate) GetFigshareUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FigshareUrl.Get(), o.FigshareUrl.IsSet()
}

// SetFigshareUrl sets field value
func (o *ProjectCompletePrivate) SetFigshareUrl(v string) {
	o.FigshareUrl.Set(&v)
}

// GetCollaborators returns the Collaborators field value
func (o *ProjectCompletePrivate) GetCollaborators() []Collaborator {
	if o == nil {
		var ret []Collaborator
		return ret
	}

	return o.Collaborators
}

// GetCollaboratorsOk returns a tuple with the Collaborators field value
// and a boolean to check if the value has been set.
func (o *ProjectCompletePrivate) GetCollaboratorsOk() ([]Collaborator, bool) {
	if o == nil {
		return nil, false
	}
	return o.Collaborators, true
}

// SetCollaborators sets field value
func (o *ProjectCompletePrivate) SetCollaborators(v []Collaborator) {
	o.Collaborators = v
}

// GetQuota returns the Quota field value
func (o *ProjectCompletePrivate) GetQuota() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Quota
}

// GetQuotaOk returns a tuple with the Quota field value
// and a boolean to check if the value has been set.
func (o *ProjectCompletePrivate) GetQuotaOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Quota, true
}

// SetQuota sets field value
func (o *ProjectCompletePrivate) SetQuota(v int64) {
	o.Quota = v
}

// GetUsedQuota returns the UsedQuota field value
func (o *ProjectCompletePrivate) GetUsedQuota() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.UsedQuota
}

// GetUsedQuotaOk returns a tuple with the UsedQuota field value
// and a boolean to check if the value has been set.
func (o *ProjectCompletePrivate) GetUsedQuotaOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UsedQuota, true
}

// SetUsedQuota sets field value
func (o *ProjectCompletePrivate) SetUsedQuota(v int64) {
	o.UsedQuota = v
}

// GetCreatedDate returns the CreatedDate field value
func (o *ProjectCompletePrivate) GetCreatedDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedDate
}

// GetCreatedDateOk returns a tuple with the CreatedDate field value
// and a boolean to check if the value has been set.
func (o *ProjectCompletePrivate) GetCreatedDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedDate, true
}

// SetCreatedDate sets field value
func (o *ProjectCompletePrivate) SetCreatedDate(v string) {
	o.CreatedDate = v
}

// GetModifiedDate returns the ModifiedDate field value
func (o *ProjectCompletePrivate) GetModifiedDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ModifiedDate
}

// GetModifiedDateOk returns a tuple with the ModifiedDate field value
// and a boolean to check if the value has been set.
func (o *ProjectCompletePrivate) GetModifiedDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ModifiedDate, true
}

// SetModifiedDate sets field value
func (o *ProjectCompletePrivate) SetModifiedDate(v string) {
	o.ModifiedDate = v
}

// GetUsedQuotaPrivate returns the UsedQuotaPrivate field value
func (o *ProjectCompletePrivate) GetUsedQuotaPrivate() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.UsedQuotaPrivate
}

// GetUsedQuotaPrivateOk returns a tuple with the UsedQuotaPrivate field value
// and a boolean to check if the value has been set.
func (o *ProjectCompletePrivate) GetUsedQuotaPrivateOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UsedQuotaPrivate, true
}

// SetUsedQuotaPrivate sets field value
func (o *ProjectCompletePrivate) SetUsedQuotaPrivate(v int64) {
	o.UsedQuotaPrivate = v
}

// GetUsedQuotaPublic returns the UsedQuotaPublic field value
func (o *ProjectCompletePrivate) GetUsedQuotaPublic() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.UsedQuotaPublic
}

// GetUsedQuotaPublicOk returns a tuple with the UsedQuotaPublic field value
// and a boolean to check if the value has been set.
func (o *ProjectCompletePrivate) GetUsedQuotaPublicOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UsedQuotaPublic, true
}

// SetUsedQuotaPublic sets field value
func (o *ProjectCompletePrivate) SetUsedQuotaPublic(v int64) {
	o.UsedQuotaPublic = v
}

// GetGroupId returns the GroupId field value
func (o *ProjectCompletePrivate) GetGroupId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.GroupId
}

// GetGroupIdOk returns a tuple with the GroupId field value
// and a boolean to check if the value has been set.
func (o *ProjectCompletePrivate) GetGroupIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GroupId, true
}

// SetGroupId sets field value
func (o *ProjectCompletePrivate) SetGroupId(v int64) {
	o.GroupId = v
}

// GetAccountId returns the AccountId field value
func (o *ProjectCompletePrivate) GetAccountId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *ProjectCompletePrivate) GetAccountIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *ProjectCompletePrivate) SetAccountId(v int64) {
	o.AccountId = v
}

// GetCustomFields returns the CustomFields field value
func (o *ProjectCompletePrivate) GetCustomFields() []ShortCustomField {
	if o == nil {
		var ret []ShortCustomField
		return ret
	}

	return o.CustomFields
}

// GetCustomFieldsOk returns a tuple with the CustomFields field value
// and a boolean to check if the value has been set.
func (o *ProjectCompletePrivate) GetCustomFieldsOk() ([]ShortCustomField, bool) {
	if o == nil {
		return nil, false
	}
	return o.CustomFields, true
}

// SetCustomFields sets field value
func (o *ProjectCompletePrivate) SetCustomFields(v []ShortCustomField) {
	o.CustomFields = v
}

// GetRole returns the Role field value
func (o *ProjectCompletePrivate) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *ProjectCompletePrivate) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *ProjectCompletePrivate) SetRole(v string) {
	o.Role = v
}

// GetStorage returns the Storage field value
func (o *ProjectCompletePrivate) GetStorage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Storage
}

// GetStorageOk returns a tuple with the Storage field value
// and a boolean to check if the value has been set.
func (o *ProjectCompletePrivate) GetStorageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Storage, true
}

// SetStorage sets field value
func (o *ProjectCompletePrivate) SetStorage(v string) {
	o.Storage = v
}

// GetUrl returns the Url field value
func (o *ProjectCompletePrivate) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *ProjectCompletePrivate) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *ProjectCompletePrivate) SetUrl(v string) {
	o.Url = v
}

// GetPublishedDate returns the PublishedDate field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ProjectCompletePrivate) GetPublishedDate() string {
	if o == nil || o.PublishedDate.Get() == nil {
		var ret string
		return ret
	}

	return *o.PublishedDate.Get()
}

// GetPublishedDateOk returns a tuple with the PublishedDate field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProjectCompletePrivate) GetPublishedDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PublishedDate.Get(), o.PublishedDate.IsSet()
}

// SetPublishedDate sets field value
func (o *ProjectCompletePrivate) SetPublishedDate(v string) {
	o.PublishedDate.Set(&v)
}

// GetId returns the Id field value
func (o *ProjectCompletePrivate) GetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ProjectCompletePrivate) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ProjectCompletePrivate) SetId(v int64) {
	o.Id = v
}

// GetTitle returns the Title field value
func (o *ProjectCompletePrivate) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *ProjectCompletePrivate) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *ProjectCompletePrivate) SetTitle(v string) {
	o.Title = v
}

func (o ProjectCompletePrivate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectCompletePrivate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["funding"] = o.Funding
	toSerialize["funding_list"] = o.FundingList
	toSerialize["description"] = o.Description
	toSerialize["figshare_url"] = o.FigshareUrl.Get()
	toSerialize["collaborators"] = o.Collaborators
	toSerialize["quota"] = o.Quota
	toSerialize["used_quota"] = o.UsedQuota
	toSerialize["created_date"] = o.CreatedDate
	toSerialize["modified_date"] = o.ModifiedDate
	toSerialize["used_quota_private"] = o.UsedQuotaPrivate
	toSerialize["used_quota_public"] = o.UsedQuotaPublic
	toSerialize["group_id"] = o.GroupId
	toSerialize["account_id"] = o.AccountId
	toSerialize["custom_fields"] = o.CustomFields
	toSerialize["role"] = o.Role
	toSerialize["storage"] = o.Storage
	toSerialize["url"] = o.Url
	toSerialize["published_date"] = o.PublishedDate.Get()
	toSerialize["id"] = o.Id
	toSerialize["title"] = o.Title
	return toSerialize, nil
}

func (o *ProjectCompletePrivate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"funding",
		"funding_list",
		"description",
		"figshare_url",
		"collaborators",
		"quota",
		"used_quota",
		"created_date",
		"modified_date",
		"used_quota_private",
		"used_quota_public",
		"group_id",
		"account_id",
		"custom_fields",
		"role",
		"storage",
		"url",
		"published_date",
		"id",
		"title",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProjectCompletePrivate := _ProjectCompletePrivate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProjectCompletePrivate)

	if err != nil {
		return err
	}

	*o = ProjectCompletePrivate(varProjectCompletePrivate)

	return err
}

type NullableProjectCompletePrivate struct {
	value *ProjectCompletePrivate
	isSet bool
}

func (v NullableProjectCompletePrivate) Get() *ProjectCompletePrivate {
	return v.value
}

func (v *NullableProjectCompletePrivate) Set(val *ProjectCompletePrivate) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectCompletePrivate) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectCompletePrivate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectCompletePrivate(val *ProjectCompletePrivate) *NullableProjectCompletePrivate {
	return &NullableProjectCompletePrivate{value: val, isSet: true}
}

func (v NullableProjectCompletePrivate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectCompletePrivate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


