/*
Figshare API

Figshare apiv2. Using Swagger 2.0

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package go_figshare

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ArticlesCreator type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ArticlesCreator{}

// ArticlesCreator struct for ArticlesCreator
type ArticlesCreator struct {
	// List of article ids
	Articles []int64 `json:"articles"`
}

type _ArticlesCreator ArticlesCreator

// NewArticlesCreator instantiates a new ArticlesCreator object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewArticlesCreator(articles []int64) *ArticlesCreator {
	this := ArticlesCreator{}
	this.Articles = articles
	return &this
}

// NewArticlesCreatorWithDefaults instantiates a new ArticlesCreator object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewArticlesCreatorWithDefaults() *ArticlesCreator {
	this := ArticlesCreator{}
	return &this
}

// GetArticles returns the Articles field value
func (o *ArticlesCreator) GetArticles() []int64 {
	if o == nil {
		var ret []int64
		return ret
	}

	return o.Articles
}

// GetArticlesOk returns a tuple with the Articles field value
// and a boolean to check if the value has been set.
func (o *ArticlesCreator) GetArticlesOk() ([]int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Articles, true
}

// SetArticles sets field value
func (o *ArticlesCreator) SetArticles(v []int64) {
	o.Articles = v
}

func (o ArticlesCreator) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ArticlesCreator) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["articles"] = o.Articles
	return toSerialize, nil
}

func (o *ArticlesCreator) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"articles",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varArticlesCreator := _ArticlesCreator{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varArticlesCreator)

	if err != nil {
		return err
	}

	*o = ArticlesCreator(varArticlesCreator)

	return err
}

type NullableArticlesCreator struct {
	value *ArticlesCreator
	isSet bool
}

func (v NullableArticlesCreator) Get() *ArticlesCreator {
	return v.value
}

func (v *NullableArticlesCreator) Set(val *ArticlesCreator) {
	v.value = val
	v.isSet = true
}

func (v NullableArticlesCreator) IsSet() bool {
	return v.isSet
}

func (v *NullableArticlesCreator) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableArticlesCreator(val *ArticlesCreator) *NullableArticlesCreator {
	return &NullableArticlesCreator{value: val, isSet: true}
}

func (v NullableArticlesCreator) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableArticlesCreator) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


