/*
Figshare API

Figshare apiv2. Using OpenApi 3.1.0

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package go_figshare

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ProjectArticle type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectArticle{}

// ProjectArticle struct for ProjectArticle
type ProjectArticle struct {
	// Article citation
	Citation string `json:"citation"`
	// Confidentiality reason
	ConfidentialReason string `json:"confidential_reason"`
	// Article embargo
	EmbargoType string `json:"embargo_type"`
	// Article Confidentiality
	IsConfidential bool `json:"is_confidential"`
	// Article size
	Size int64 `json:"size"`
	// Article funding
	Funding string `json:"funding"`
	// List of article tags. Keywords can be used instead
	Tags []string `json:"tags"`
	// List of article keywords. Tags can be used instead
	Keywords []string `json:"keywords"`
	// Article version
	Version int64 `json:"version"`
	// True if article has no files
	IsMetadataRecord bool `json:"is_metadata_record"`
	// Article metadata reason
	MetadataReason string `json:"metadata_reason"`
	// Article status
	Status string `json:"status"`
	// Article description
	Description string `json:"description"`
	// True if article is embargoed
	IsEmbargoed bool `json:"is_embargoed"`
	// Date when embargo lifts
	EmbargoDate string `json:"embargo_date"`
	// True if article is published
	IsPublic bool `json:"is_public"`
	// Date when article was last modified
	ModifiedDate string `json:"modified_date"`
	// Date when article was created
	CreatedDate string `json:"created_date"`
	// True if any files are linked to the article
	HasLinkedFile bool `json:"has_linked_file"`
	// List of categories selected for the article
	Categories []Category `json:"categories"`
	// Article selected license
	License License `json:"license"`
	// Title for embargo
	EmbargoTitle string `json:"embargo_title"`
	// Reason for embargo
	EmbargoReason string `json:"embargo_reason"`
	// List of references
	References []string `json:"references"`
	// Unique identifier for article
	Id int64 `json:"id"`
	// Title of article
	Title string `json:"title"`
	// DOI
	Doi string `json:"doi"`
	// Handle
	Handle string `json:"handle"`
	// Group ID
	GroupId NullableFloat32 `json:"group_id"`
	// Api endpoint for article
	Url string `json:"url"`
	// Public site endpoint for article
	UrlPublicHtml string `json:"url_public_html"`
	// Public Api endpoint for article
	UrlPublicApi string `json:"url_public_api"`
	// Private site endpoint for article
	UrlPrivateHtml string `json:"url_private_html"`
	// Private Api endpoint for article
	UrlPrivateApi string `json:"url_private_api"`
	// Posted date
	PublishedDate NullableString `json:"published_date"`
	// Thumbnail image
	Thumb string `json:"thumb"`
	// Type of article identifier
	DefinedType int64 `json:"defined_type"`
	// Name of the article type identifier
	DefinedTypeName string `json:"defined_type_name"`
	// Deprecated by related materials. Not applicable to regular users. In a publisher case, this is the publisher article DOI.
	ResourceDoi string `json:"resource_doi"`
	// Deprecated by related materials. Not applicable to regular users. In a publisher case, this is the publisher article title.
	ResourceTitle string `json:"resource_title"`
}

type _ProjectArticle ProjectArticle

// NewProjectArticle instantiates a new ProjectArticle object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectArticle(citation string, confidentialReason string, embargoType string, isConfidential bool, size int64, funding string, tags []string, keywords []string, version int64, isMetadataRecord bool, metadataReason string, status string, description string, isEmbargoed bool, embargoDate string, isPublic bool, modifiedDate string, createdDate string, hasLinkedFile bool, categories []Category, license License, embargoTitle string, embargoReason string, references []string, id int64, title string, doi string, handle string, groupId NullableFloat32, url string, urlPublicHtml string, urlPublicApi string, urlPrivateHtml string, urlPrivateApi string, publishedDate NullableString, thumb string, definedType int64, definedTypeName string, resourceDoi string, resourceTitle string) *ProjectArticle {
	this := ProjectArticle{}
	this.Id = id
	this.Title = title
	this.Doi = doi
	this.Handle = handle
	this.GroupId = groupId
	this.Url = url
	this.UrlPublicHtml = urlPublicHtml
	this.UrlPublicApi = urlPublicApi
	this.UrlPrivateHtml = urlPrivateHtml
	this.UrlPrivateApi = urlPrivateApi
	this.PublishedDate = publishedDate
	this.Thumb = thumb
	this.DefinedType = definedType
	this.DefinedTypeName = definedTypeName
	this.ResourceDoi = resourceDoi
	this.ResourceTitle = resourceTitle
	this.CreatedDate = createdDate
	this.ModifiedDate = modifiedDate
	return &this
}

// NewProjectArticleWithDefaults instantiates a new ProjectArticle object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectArticleWithDefaults() *ProjectArticle {
	this := ProjectArticle{}
	var resourceDoi string = ""
	this.ResourceDoi = resourceDoi
	var resourceTitle string = ""
	this.ResourceTitle = resourceTitle
	return &this
}

// GetCitation returns the Citation field value
func (o *ProjectArticle) GetCitation() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Citation
}

// GetCitationOk returns a tuple with the Citation field value
// and a boolean to check if the value has been set.
func (o *ProjectArticle) GetCitationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Citation, true
}

// SetCitation sets field value
func (o *ProjectArticle) SetCitation(v string) {
	o.Citation = v
}

// GetConfidentialReason returns the ConfidentialReason field value
func (o *ProjectArticle) GetConfidentialReason() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConfidentialReason
}

// GetConfidentialReasonOk returns a tuple with the ConfidentialReason field value
// and a boolean to check if the value has been set.
func (o *ProjectArticle) GetConfidentialReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConfidentialReason, true
}

// SetConfidentialReason sets field value
func (o *ProjectArticle) SetConfidentialReason(v string) {
	o.ConfidentialReason = v
}

// GetEmbargoType returns the EmbargoType field value
func (o *ProjectArticle) GetEmbargoType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EmbargoType
}

// GetEmbargoTypeOk returns a tuple with the EmbargoType field value
// and a boolean to check if the value has been set.
func (o *ProjectArticle) GetEmbargoTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EmbargoType, true
}

// SetEmbargoType sets field value
func (o *ProjectArticle) SetEmbargoType(v string) {
	o.EmbargoType = v
}

// GetIsConfidential returns the IsConfidential field value
func (o *ProjectArticle) GetIsConfidential() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsConfidential
}

// GetIsConfidentialOk returns a tuple with the IsConfidential field value
// and a boolean to check if the value has been set.
func (o *ProjectArticle) GetIsConfidentialOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsConfidential, true
}

// SetIsConfidential sets field value
func (o *ProjectArticle) SetIsConfidential(v bool) {
	o.IsConfidential = v
}

// GetSize returns the Size field value
func (o *ProjectArticle) GetSize() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Size
}

// GetSizeOk returns a tuple with the Size field value
// and a boolean to check if the value has been set.
func (o *ProjectArticle) GetSizeOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Size, true
}

// SetSize sets field value
func (o *ProjectArticle) SetSize(v int64) {
	o.Size = v
}

// GetFunding returns the Funding field value
func (o *ProjectArticle) GetFunding() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Funding
}

// GetFundingOk returns a tuple with the Funding field value
// and a boolean to check if the value has been set.
func (o *ProjectArticle) GetFundingOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Funding, true
}

// SetFunding sets field value
func (o *ProjectArticle) SetFunding(v string) {
	o.Funding = v
}

// GetTags returns the Tags field value
func (o *ProjectArticle) GetTags() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value
// and a boolean to check if the value has been set.
func (o *ProjectArticle) GetTagsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tags, true
}

// SetTags sets field value
func (o *ProjectArticle) SetTags(v []string) {
	o.Tags = v
}

// GetKeywords returns the Keywords field value
func (o *ProjectArticle) GetKeywords() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Keywords
}

// GetKeywordsOk returns a tuple with the Keywords field value
// and a boolean to check if the value has been set.
func (o *ProjectArticle) GetKeywordsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Keywords, true
}

// SetKeywords sets field value
func (o *ProjectArticle) SetKeywords(v []string) {
	o.Keywords = v
}

// GetVersion returns the Version field value
func (o *ProjectArticle) GetVersion() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *ProjectArticle) GetVersionOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *ProjectArticle) SetVersion(v int64) {
	o.Version = v
}

// GetIsMetadataRecord returns the IsMetadataRecord field value
func (o *ProjectArticle) GetIsMetadataRecord() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsMetadataRecord
}

// GetIsMetadataRecordOk returns a tuple with the IsMetadataRecord field value
// and a boolean to check if the value has been set.
func (o *ProjectArticle) GetIsMetadataRecordOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsMetadataRecord, true
}

// SetIsMetadataRecord sets field value
func (o *ProjectArticle) SetIsMetadataRecord(v bool) {
	o.IsMetadataRecord = v
}

// GetMetadataReason returns the MetadataReason field value
func (o *ProjectArticle) GetMetadataReason() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MetadataReason
}

// GetMetadataReasonOk returns a tuple with the MetadataReason field value
// and a boolean to check if the value has been set.
func (o *ProjectArticle) GetMetadataReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MetadataReason, true
}

// SetMetadataReason sets field value
func (o *ProjectArticle) SetMetadataReason(v string) {
	o.MetadataReason = v
}

// GetStatus returns the Status field value
func (o *ProjectArticle) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ProjectArticle) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ProjectArticle) SetStatus(v string) {
	o.Status = v
}

// GetDescription returns the Description field value
func (o *ProjectArticle) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *ProjectArticle) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *ProjectArticle) SetDescription(v string) {
	o.Description = v
}

// GetIsEmbargoed returns the IsEmbargoed field value
func (o *ProjectArticle) GetIsEmbargoed() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsEmbargoed
}

// GetIsEmbargoedOk returns a tuple with the IsEmbargoed field value
// and a boolean to check if the value has been set.
func (o *ProjectArticle) GetIsEmbargoedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsEmbargoed, true
}

// SetIsEmbargoed sets field value
func (o *ProjectArticle) SetIsEmbargoed(v bool) {
	o.IsEmbargoed = v
}

// GetEmbargoDate returns the EmbargoDate field value
func (o *ProjectArticle) GetEmbargoDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EmbargoDate
}

// GetEmbargoDateOk returns a tuple with the EmbargoDate field value
// and a boolean to check if the value has been set.
func (o *ProjectArticle) GetEmbargoDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EmbargoDate, true
}

// SetEmbargoDate sets field value
func (o *ProjectArticle) SetEmbargoDate(v string) {
	o.EmbargoDate = v
}

// GetIsPublic returns the IsPublic field value
func (o *ProjectArticle) GetIsPublic() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsPublic
}

// GetIsPublicOk returns a tuple with the IsPublic field value
// and a boolean to check if the value has been set.
func (o *ProjectArticle) GetIsPublicOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsPublic, true
}

// SetIsPublic sets field value
func (o *ProjectArticle) SetIsPublic(v bool) {
	o.IsPublic = v
}

// GetModifiedDate returns the ModifiedDate field value
func (o *ProjectArticle) GetModifiedDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ModifiedDate
}

// GetModifiedDateOk returns a tuple with the ModifiedDate field value
// and a boolean to check if the value has been set.
func (o *ProjectArticle) GetModifiedDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ModifiedDate, true
}

// SetModifiedDate sets field value
func (o *ProjectArticle) SetModifiedDate(v string) {
	o.ModifiedDate = v
}

// GetCreatedDate returns the CreatedDate field value
func (o *ProjectArticle) GetCreatedDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedDate
}

// GetCreatedDateOk returns a tuple with the CreatedDate field value
// and a boolean to check if the value has been set.
func (o *ProjectArticle) GetCreatedDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedDate, true
}

// SetCreatedDate sets field value
func (o *ProjectArticle) SetCreatedDate(v string) {
	o.CreatedDate = v
}

// GetHasLinkedFile returns the HasLinkedFile field value
func (o *ProjectArticle) GetHasLinkedFile() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasLinkedFile
}

// GetHasLinkedFileOk returns a tuple with the HasLinkedFile field value
// and a boolean to check if the value has been set.
func (o *ProjectArticle) GetHasLinkedFileOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasLinkedFile, true
}

// SetHasLinkedFile sets field value
func (o *ProjectArticle) SetHasLinkedFile(v bool) {
	o.HasLinkedFile = v
}

// GetCategories returns the Categories field value
func (o *ProjectArticle) GetCategories() []Category {
	if o == nil {
		var ret []Category
		return ret
	}

	return o.Categories
}

// GetCategoriesOk returns a tuple with the Categories field value
// and a boolean to check if the value has been set.
func (o *ProjectArticle) GetCategoriesOk() ([]Category, bool) {
	if o == nil {
		return nil, false
	}
	return o.Categories, true
}

// SetCategories sets field value
func (o *ProjectArticle) SetCategories(v []Category) {
	o.Categories = v
}

// GetLicense returns the License field value
func (o *ProjectArticle) GetLicense() License {
	if o == nil {
		var ret License
		return ret
	}

	return o.License
}

// GetLicenseOk returns a tuple with the License field value
// and a boolean to check if the value has been set.
func (o *ProjectArticle) GetLicenseOk() (*License, bool) {
	if o == nil {
		return nil, false
	}
	return &o.License, true
}

// SetLicense sets field value
func (o *ProjectArticle) SetLicense(v License) {
	o.License = v
}

// GetEmbargoTitle returns the EmbargoTitle field value
func (o *ProjectArticle) GetEmbargoTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EmbargoTitle
}

// GetEmbargoTitleOk returns a tuple with the EmbargoTitle field value
// and a boolean to check if the value has been set.
func (o *ProjectArticle) GetEmbargoTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EmbargoTitle, true
}

// SetEmbargoTitle sets field value
func (o *ProjectArticle) SetEmbargoTitle(v string) {
	o.EmbargoTitle = v
}

// GetEmbargoReason returns the EmbargoReason field value
func (o *ProjectArticle) GetEmbargoReason() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EmbargoReason
}

// GetEmbargoReasonOk returns a tuple with the EmbargoReason field value
// and a boolean to check if the value has been set.
func (o *ProjectArticle) GetEmbargoReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EmbargoReason, true
}

// SetEmbargoReason sets field value
func (o *ProjectArticle) SetEmbargoReason(v string) {
	o.EmbargoReason = v
}

// GetReferences returns the References field value
func (o *ProjectArticle) GetReferences() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.References
}

// GetReferencesOk returns a tuple with the References field value
// and a boolean to check if the value has been set.
func (o *ProjectArticle) GetReferencesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.References, true
}

// SetReferences sets field value
func (o *ProjectArticle) SetReferences(v []string) {
	o.References = v
}

// GetId returns the Id field value
func (o *ProjectArticle) GetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ProjectArticle) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ProjectArticle) SetId(v int64) {
	o.Id = v
}

// GetTitle returns the Title field value
func (o *ProjectArticle) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *ProjectArticle) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *ProjectArticle) SetTitle(v string) {
	o.Title = v
}

// GetDoi returns the Doi field value
func (o *ProjectArticle) GetDoi() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Doi
}

// GetDoiOk returns a tuple with the Doi field value
// and a boolean to check if the value has been set.
func (o *ProjectArticle) GetDoiOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Doi, true
}

// SetDoi sets field value
func (o *ProjectArticle) SetDoi(v string) {
	o.Doi = v
}

// GetHandle returns the Handle field value
func (o *ProjectArticle) GetHandle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Handle
}

// GetHandleOk returns a tuple with the Handle field value
// and a boolean to check if the value has been set.
func (o *ProjectArticle) GetHandleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Handle, true
}

// SetHandle sets field value
func (o *ProjectArticle) SetHandle(v string) {
	o.Handle = v
}

// GetGroupId returns the GroupId field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *ProjectArticle) GetGroupId() float32 {
	if o == nil || o.GroupId.Get() == nil {
		var ret float32
		return ret
	}

	return *o.GroupId.Get()
}

// GetGroupIdOk returns a tuple with the GroupId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProjectArticle) GetGroupIdOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.GroupId.Get(), o.GroupId.IsSet()
}

// SetGroupId sets field value
func (o *ProjectArticle) SetGroupId(v float32) {
	o.GroupId.Set(&v)
}

// GetUrl returns the Url field value
func (o *ProjectArticle) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *ProjectArticle) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *ProjectArticle) SetUrl(v string) {
	o.Url = v
}

// GetUrlPublicHtml returns the UrlPublicHtml field value
func (o *ProjectArticle) GetUrlPublicHtml() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UrlPublicHtml
}

// GetUrlPublicHtmlOk returns a tuple with the UrlPublicHtml field value
// and a boolean to check if the value has been set.
func (o *ProjectArticle) GetUrlPublicHtmlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UrlPublicHtml, true
}

// SetUrlPublicHtml sets field value
func (o *ProjectArticle) SetUrlPublicHtml(v string) {
	o.UrlPublicHtml = v
}

// GetUrlPublicApi returns the UrlPublicApi field value
func (o *ProjectArticle) GetUrlPublicApi() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UrlPublicApi
}

// GetUrlPublicApiOk returns a tuple with the UrlPublicApi field value
// and a boolean to check if the value has been set.
func (o *ProjectArticle) GetUrlPublicApiOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UrlPublicApi, true
}

// SetUrlPublicApi sets field value
func (o *ProjectArticle) SetUrlPublicApi(v string) {
	o.UrlPublicApi = v
}

// GetUrlPrivateHtml returns the UrlPrivateHtml field value
func (o *ProjectArticle) GetUrlPrivateHtml() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UrlPrivateHtml
}

// GetUrlPrivateHtmlOk returns a tuple with the UrlPrivateHtml field value
// and a boolean to check if the value has been set.
func (o *ProjectArticle) GetUrlPrivateHtmlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UrlPrivateHtml, true
}

// SetUrlPrivateHtml sets field value
func (o *ProjectArticle) SetUrlPrivateHtml(v string) {
	o.UrlPrivateHtml = v
}

// GetUrlPrivateApi returns the UrlPrivateApi field value
func (o *ProjectArticle) GetUrlPrivateApi() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UrlPrivateApi
}

// GetUrlPrivateApiOk returns a tuple with the UrlPrivateApi field value
// and a boolean to check if the value has been set.
func (o *ProjectArticle) GetUrlPrivateApiOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UrlPrivateApi, true
}

// SetUrlPrivateApi sets field value
func (o *ProjectArticle) SetUrlPrivateApi(v string) {
	o.UrlPrivateApi = v
}

// GetPublishedDate returns the PublishedDate field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ProjectArticle) GetPublishedDate() string {
	if o == nil || o.PublishedDate.Get() == nil {
		var ret string
		return ret
	}

	return *o.PublishedDate.Get()
}

// GetPublishedDateOk returns a tuple with the PublishedDate field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProjectArticle) GetPublishedDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PublishedDate.Get(), o.PublishedDate.IsSet()
}

// SetPublishedDate sets field value
func (o *ProjectArticle) SetPublishedDate(v string) {
	o.PublishedDate.Set(&v)
}

// GetThumb returns the Thumb field value
func (o *ProjectArticle) GetThumb() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Thumb
}

// GetThumbOk returns a tuple with the Thumb field value
// and a boolean to check if the value has been set.
func (o *ProjectArticle) GetThumbOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Thumb, true
}

// SetThumb sets field value
func (o *ProjectArticle) SetThumb(v string) {
	o.Thumb = v
}

// GetDefinedType returns the DefinedType field value
func (o *ProjectArticle) GetDefinedType() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.DefinedType
}

// GetDefinedTypeOk returns a tuple with the DefinedType field value
// and a boolean to check if the value has been set.
func (o *ProjectArticle) GetDefinedTypeOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DefinedType, true
}

// SetDefinedType sets field value
func (o *ProjectArticle) SetDefinedType(v int64) {
	o.DefinedType = v
}

// GetDefinedTypeName returns the DefinedTypeName field value
func (o *ProjectArticle) GetDefinedTypeName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DefinedTypeName
}

// GetDefinedTypeNameOk returns a tuple with the DefinedTypeName field value
// and a boolean to check if the value has been set.
func (o *ProjectArticle) GetDefinedTypeNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DefinedTypeName, true
}

// SetDefinedTypeName sets field value
func (o *ProjectArticle) SetDefinedTypeName(v string) {
	o.DefinedTypeName = v
}

// GetResourceDoi returns the ResourceDoi field value
func (o *ProjectArticle) GetResourceDoi() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResourceDoi
}

// GetResourceDoiOk returns a tuple with the ResourceDoi field value
// and a boolean to check if the value has been set.
func (o *ProjectArticle) GetResourceDoiOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResourceDoi, true
}

// SetResourceDoi sets field value
func (o *ProjectArticle) SetResourceDoi(v string) {
	o.ResourceDoi = v
}

// GetResourceTitle returns the ResourceTitle field value
func (o *ProjectArticle) GetResourceTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResourceTitle
}

// GetResourceTitleOk returns a tuple with the ResourceTitle field value
// and a boolean to check if the value has been set.
func (o *ProjectArticle) GetResourceTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResourceTitle, true
}

// SetResourceTitle sets field value
func (o *ProjectArticle) SetResourceTitle(v string) {
	o.ResourceTitle = v
}

func (o ProjectArticle) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectArticle) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["citation"] = o.Citation
	toSerialize["confidential_reason"] = o.ConfidentialReason
	toSerialize["embargo_type"] = o.EmbargoType
	toSerialize["is_confidential"] = o.IsConfidential
	toSerialize["size"] = o.Size
	toSerialize["funding"] = o.Funding
	toSerialize["tags"] = o.Tags
	toSerialize["keywords"] = o.Keywords
	toSerialize["version"] = o.Version
	toSerialize["is_metadata_record"] = o.IsMetadataRecord
	toSerialize["metadata_reason"] = o.MetadataReason
	toSerialize["status"] = o.Status
	toSerialize["description"] = o.Description
	toSerialize["is_embargoed"] = o.IsEmbargoed
	toSerialize["embargo_date"] = o.EmbargoDate
	toSerialize["is_public"] = o.IsPublic
	toSerialize["modified_date"] = o.ModifiedDate
	toSerialize["created_date"] = o.CreatedDate
	toSerialize["has_linked_file"] = o.HasLinkedFile
	toSerialize["categories"] = o.Categories
	toSerialize["license"] = o.License
	toSerialize["embargo_title"] = o.EmbargoTitle
	toSerialize["embargo_reason"] = o.EmbargoReason
	toSerialize["references"] = o.References
	toSerialize["id"] = o.Id
	toSerialize["title"] = o.Title
	toSerialize["doi"] = o.Doi
	toSerialize["handle"] = o.Handle
	toSerialize["group_id"] = o.GroupId.Get()
	toSerialize["url"] = o.Url
	toSerialize["url_public_html"] = o.UrlPublicHtml
	toSerialize["url_public_api"] = o.UrlPublicApi
	toSerialize["url_private_html"] = o.UrlPrivateHtml
	toSerialize["url_private_api"] = o.UrlPrivateApi
	toSerialize["published_date"] = o.PublishedDate.Get()
	toSerialize["thumb"] = o.Thumb
	toSerialize["defined_type"] = o.DefinedType
	toSerialize["defined_type_name"] = o.DefinedTypeName
	toSerialize["resource_doi"] = o.ResourceDoi
	toSerialize["resource_title"] = o.ResourceTitle
	return toSerialize, nil
}

func (o *ProjectArticle) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"citation",
		"confidential_reason",
		"embargo_type",
		"is_confidential",
		"size",
		"funding",
		"tags",
		"keywords",
		"version",
		"is_metadata_record",
		"metadata_reason",
		"status",
		"description",
		"is_embargoed",
		"embargo_date",
		"is_public",
		"modified_date",
		"created_date",
		"has_linked_file",
		"categories",
		"license",
		"embargo_title",
		"embargo_reason",
		"references",
		"id",
		"title",
		"doi",
		"handle",
		"group_id",
		"url",
		"url_public_html",
		"url_public_api",
		"url_private_html",
		"url_private_api",
		"published_date",
		"thumb",
		"defined_type",
		"defined_type_name",
		"resource_doi",
		"resource_title",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProjectArticle := _ProjectArticle{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProjectArticle)

	if err != nil {
		return err
	}

	*o = ProjectArticle(varProjectArticle)

	return err
}

type NullableProjectArticle struct {
	value *ProjectArticle
	isSet bool
}

func (v NullableProjectArticle) Get() *ProjectArticle {
	return v.value
}

func (v *NullableProjectArticle) Set(val *ProjectArticle) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectArticle) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectArticle) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectArticle(val *ProjectArticle) *NullableProjectArticle {
	return &NullableProjectArticle{value: val, isSet: true}
}

func (v NullableProjectArticle) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectArticle) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


