/*
Figshare API

Figshare apiv2. Using Swagger 2.0

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package figshare

import (
	"encoding/json"
)

// checks if the PrivateLinkCreator type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PrivateLinkCreator{}

// PrivateLinkCreator struct for PrivateLinkCreator
type PrivateLinkCreator struct {
	// Date when this private link should expire - optional. By default private links expire in 365 days.
	ExpiresDate *string `json:"expires_date,omitempty"`
}

// NewPrivateLinkCreator instantiates a new PrivateLinkCreator object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPrivateLinkCreator() *PrivateLinkCreator {
	this := PrivateLinkCreator{}
	return &this
}

// NewPrivateLinkCreatorWithDefaults instantiates a new PrivateLinkCreator object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPrivateLinkCreatorWithDefaults() *PrivateLinkCreator {
	this := PrivateLinkCreator{}
	return &this
}

// GetExpiresDate returns the ExpiresDate field value if set, zero value otherwise.
func (o *PrivateLinkCreator) GetExpiresDate() string {
	if o == nil || IsNil(o.ExpiresDate) {
		var ret string
		return ret
	}
	return *o.ExpiresDate
}

// GetExpiresDateOk returns a tuple with the ExpiresDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrivateLinkCreator) GetExpiresDateOk() (*string, bool) {
	if o == nil || IsNil(o.ExpiresDate) {
		return nil, false
	}
	return o.ExpiresDate, true
}

// HasExpiresDate returns a boolean if a field has been set.
func (o *PrivateLinkCreator) HasExpiresDate() bool {
	if o != nil && !IsNil(o.ExpiresDate) {
		return true
	}

	return false
}

// SetExpiresDate gets a reference to the given string and assigns it to the ExpiresDate field.
func (o *PrivateLinkCreator) SetExpiresDate(v string) {
	o.ExpiresDate = &v
}

func (o PrivateLinkCreator) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PrivateLinkCreator) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ExpiresDate) {
		toSerialize["expires_date"] = o.ExpiresDate
	}
	return toSerialize, nil
}

type NullablePrivateLinkCreator struct {
	value *PrivateLinkCreator
	isSet bool
}

func (v NullablePrivateLinkCreator) Get() *PrivateLinkCreator {
	return v.value
}

func (v *NullablePrivateLinkCreator) Set(val *PrivateLinkCreator) {
	v.value = val
	v.isSet = true
}

func (v NullablePrivateLinkCreator) IsSet() bool {
	return v.isSet
}

func (v *NullablePrivateLinkCreator) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePrivateLinkCreator(val *PrivateLinkCreator) *NullablePrivateLinkCreator {
	return &NullablePrivateLinkCreator{value: val, isSet: true}
}

func (v NullablePrivateLinkCreator) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePrivateLinkCreator) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


