/*
Figshare API

Figshare apiv2. Using Swagger 2.0

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PrivateFile type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PrivateFile{}

// PrivateFile struct for PrivateFile
type PrivateFile struct {
	// True if the file is attached to a public item version
	IsAttachedToPublicVersion bool `json:"is_attached_to_public_version"`
	// File preview state
	PreviewState string `json:"preview_state"`
	// Token for file upload
	UploadToken string `json:"upload_token"`
	// Upload url for file
	UploadUrl string `json:"upload_url"`
	// File viewer type
	ViewerType string `json:"viewer_type"`
	// File computed md5
	ComputedMd5 string `json:"computed_md5"`
	// Url for file download
	DownloadUrl string `json:"download_url"`
	// File id
	Id int64 `json:"id"`
	// True if file is hosted somewhere else
	IsLinkOnly bool `json:"is_link_only"`
	// MIME Type of the file, it defaults to an empty string
	Mimetype *string `json:"mimetype,omitempty"`
	// File name
	Name string `json:"name"`
	// File size
	Size int64 `json:"size"`
	// File supplied md5
	SuppliedMd5 string `json:"supplied_md5"`
}

type _PrivateFile PrivateFile

// NewPrivateFile instantiates a new PrivateFile object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPrivateFile(isAttachedToPublicVersion bool, previewState string, uploadToken string, uploadUrl string, viewerType string, computedMd5 string, downloadUrl string, id int64, isLinkOnly bool, name string, size int64, suppliedMd5 string) *PrivateFile {
	this := PrivateFile{}
	this.ComputedMd5 = computedMd5
	this.DownloadUrl = downloadUrl
	this.Id = id
	this.IsLinkOnly = isLinkOnly
	this.Name = name
	this.Size = size
	this.SuppliedMd5 = suppliedMd5
	return &this
}

// NewPrivateFileWithDefaults instantiates a new PrivateFile object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPrivateFileWithDefaults() *PrivateFile {
	this := PrivateFile{}
	return &this
}

// GetIsAttachedToPublicVersion returns the IsAttachedToPublicVersion field value
func (o *PrivateFile) GetIsAttachedToPublicVersion() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsAttachedToPublicVersion
}

// GetIsAttachedToPublicVersionOk returns a tuple with the IsAttachedToPublicVersion field value
// and a boolean to check if the value has been set.
func (o *PrivateFile) GetIsAttachedToPublicVersionOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsAttachedToPublicVersion, true
}

// SetIsAttachedToPublicVersion sets field value
func (o *PrivateFile) SetIsAttachedToPublicVersion(v bool) {
	o.IsAttachedToPublicVersion = v
}

// GetPreviewState returns the PreviewState field value
func (o *PrivateFile) GetPreviewState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PreviewState
}

// GetPreviewStateOk returns a tuple with the PreviewState field value
// and a boolean to check if the value has been set.
func (o *PrivateFile) GetPreviewStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PreviewState, true
}

// SetPreviewState sets field value
func (o *PrivateFile) SetPreviewState(v string) {
	o.PreviewState = v
}

// GetUploadToken returns the UploadToken field value
func (o *PrivateFile) GetUploadToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UploadToken
}

// GetUploadTokenOk returns a tuple with the UploadToken field value
// and a boolean to check if the value has been set.
func (o *PrivateFile) GetUploadTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UploadToken, true
}

// SetUploadToken sets field value
func (o *PrivateFile) SetUploadToken(v string) {
	o.UploadToken = v
}

// GetUploadUrl returns the UploadUrl field value
func (o *PrivateFile) GetUploadUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UploadUrl
}

// GetUploadUrlOk returns a tuple with the UploadUrl field value
// and a boolean to check if the value has been set.
func (o *PrivateFile) GetUploadUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UploadUrl, true
}

// SetUploadUrl sets field value
func (o *PrivateFile) SetUploadUrl(v string) {
	o.UploadUrl = v
}

// GetViewerType returns the ViewerType field value
func (o *PrivateFile) GetViewerType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ViewerType
}

// GetViewerTypeOk returns a tuple with the ViewerType field value
// and a boolean to check if the value has been set.
func (o *PrivateFile) GetViewerTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ViewerType, true
}

// SetViewerType sets field value
func (o *PrivateFile) SetViewerType(v string) {
	o.ViewerType = v
}

// GetComputedMd5 returns the ComputedMd5 field value
func (o *PrivateFile) GetComputedMd5() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ComputedMd5
}

// GetComputedMd5Ok returns a tuple with the ComputedMd5 field value
// and a boolean to check if the value has been set.
func (o *PrivateFile) GetComputedMd5Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ComputedMd5, true
}

// SetComputedMd5 sets field value
func (o *PrivateFile) SetComputedMd5(v string) {
	o.ComputedMd5 = v
}

// GetDownloadUrl returns the DownloadUrl field value
func (o *PrivateFile) GetDownloadUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DownloadUrl
}

// GetDownloadUrlOk returns a tuple with the DownloadUrl field value
// and a boolean to check if the value has been set.
func (o *PrivateFile) GetDownloadUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DownloadUrl, true
}

// SetDownloadUrl sets field value
func (o *PrivateFile) SetDownloadUrl(v string) {
	o.DownloadUrl = v
}

// GetId returns the Id field value
func (o *PrivateFile) GetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PrivateFile) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PrivateFile) SetId(v int64) {
	o.Id = v
}

// GetIsLinkOnly returns the IsLinkOnly field value
func (o *PrivateFile) GetIsLinkOnly() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsLinkOnly
}

// GetIsLinkOnlyOk returns a tuple with the IsLinkOnly field value
// and a boolean to check if the value has been set.
func (o *PrivateFile) GetIsLinkOnlyOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsLinkOnly, true
}

// SetIsLinkOnly sets field value
func (o *PrivateFile) SetIsLinkOnly(v bool) {
	o.IsLinkOnly = v
}

// GetMimetype returns the Mimetype field value if set, zero value otherwise.
func (o *PrivateFile) GetMimetype() string {
	if o == nil || IsNil(o.Mimetype) {
		var ret string
		return ret
	}
	return *o.Mimetype
}

// GetMimetypeOk returns a tuple with the Mimetype field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrivateFile) GetMimetypeOk() (*string, bool) {
	if o == nil || IsNil(o.Mimetype) {
		return nil, false
	}
	return o.Mimetype, true
}

// HasMimetype returns a boolean if a field has been set.
func (o *PrivateFile) HasMimetype() bool {
	if o != nil && !IsNil(o.Mimetype) {
		return true
	}

	return false
}

// SetMimetype gets a reference to the given string and assigns it to the Mimetype field.
func (o *PrivateFile) SetMimetype(v string) {
	o.Mimetype = &v
}

// GetName returns the Name field value
func (o *PrivateFile) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *PrivateFile) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *PrivateFile) SetName(v string) {
	o.Name = v
}

// GetSize returns the Size field value
func (o *PrivateFile) GetSize() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Size
}

// GetSizeOk returns a tuple with the Size field value
// and a boolean to check if the value has been set.
func (o *PrivateFile) GetSizeOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Size, true
}

// SetSize sets field value
func (o *PrivateFile) SetSize(v int64) {
	o.Size = v
}

// GetSuppliedMd5 returns the SuppliedMd5 field value
func (o *PrivateFile) GetSuppliedMd5() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SuppliedMd5
}

// GetSuppliedMd5Ok returns a tuple with the SuppliedMd5 field value
// and a boolean to check if the value has been set.
func (o *PrivateFile) GetSuppliedMd5Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SuppliedMd5, true
}

// SetSuppliedMd5 sets field value
func (o *PrivateFile) SetSuppliedMd5(v string) {
	o.SuppliedMd5 = v
}

func (o PrivateFile) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PrivateFile) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["is_attached_to_public_version"] = o.IsAttachedToPublicVersion
	toSerialize["preview_state"] = o.PreviewState
	toSerialize["upload_token"] = o.UploadToken
	toSerialize["upload_url"] = o.UploadUrl
	toSerialize["viewer_type"] = o.ViewerType
	toSerialize["computed_md5"] = o.ComputedMd5
	toSerialize["download_url"] = o.DownloadUrl
	toSerialize["id"] = o.Id
	toSerialize["is_link_only"] = o.IsLinkOnly
	if !IsNil(o.Mimetype) {
		toSerialize["mimetype"] = o.Mimetype
	}
	toSerialize["name"] = o.Name
	toSerialize["size"] = o.Size
	toSerialize["supplied_md5"] = o.SuppliedMd5
	return toSerialize, nil
}

func (o *PrivateFile) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"is_attached_to_public_version",
		"preview_state",
		"upload_token",
		"upload_url",
		"viewer_type",
		"computed_md5",
		"download_url",
		"id",
		"is_link_only",
		"name",
		"size",
		"supplied_md5",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPrivateFile := _PrivateFile{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPrivateFile)

	if err != nil {
		return err
	}

	*o = PrivateFile(varPrivateFile)

	return err
}

type NullablePrivateFile struct {
	value *PrivateFile
	isSet bool
}

func (v NullablePrivateFile) Get() *PrivateFile {
	return v.value
}

func (v *NullablePrivateFile) Set(val *PrivateFile) {
	v.value = val
	v.isSet = true
}

func (v NullablePrivateFile) IsSet() bool {
	return v.isSet
}

func (v *NullablePrivateFile) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePrivateFile(val *PrivateFile) *NullablePrivateFile {
	return &NullablePrivateFile{value: val, isSet: true}
}

func (v NullablePrivateFile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePrivateFile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


