/*
Figshare API

Figshare apiv2. Using Swagger 2.0

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PrivateLink type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PrivateLink{}

// PrivateLink struct for PrivateLink
type PrivateLink struct {
	// Date when link will expire
	ExpiresDate string `json:"expires_date"`
	// HTML url for private link
	HtmlLocation string `json:"html_location"`
	// Private link id
	Id string `json:"id"`
	// True if private link is active
	IsActive bool `json:"is_active"`
}

type _PrivateLink PrivateLink

// NewPrivateLink instantiates a new PrivateLink object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPrivateLink(expiresDate string, htmlLocation string, id string, isActive bool) *PrivateLink {
	this := PrivateLink{}
	this.ExpiresDate = expiresDate
	this.HtmlLocation = htmlLocation
	this.Id = id
	this.IsActive = isActive
	return &this
}

// NewPrivateLinkWithDefaults instantiates a new PrivateLink object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPrivateLinkWithDefaults() *PrivateLink {
	this := PrivateLink{}
	return &this
}

// GetExpiresDate returns the ExpiresDate field value
func (o *PrivateLink) GetExpiresDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExpiresDate
}

// GetExpiresDateOk returns a tuple with the ExpiresDate field value
// and a boolean to check if the value has been set.
func (o *PrivateLink) GetExpiresDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresDate, true
}

// SetExpiresDate sets field value
func (o *PrivateLink) SetExpiresDate(v string) {
	o.ExpiresDate = v
}

// GetHtmlLocation returns the HtmlLocation field value
func (o *PrivateLink) GetHtmlLocation() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.HtmlLocation
}

// GetHtmlLocationOk returns a tuple with the HtmlLocation field value
// and a boolean to check if the value has been set.
func (o *PrivateLink) GetHtmlLocationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HtmlLocation, true
}

// SetHtmlLocation sets field value
func (o *PrivateLink) SetHtmlLocation(v string) {
	o.HtmlLocation = v
}

// GetId returns the Id field value
func (o *PrivateLink) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PrivateLink) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PrivateLink) SetId(v string) {
	o.Id = v
}

// GetIsActive returns the IsActive field value
func (o *PrivateLink) GetIsActive() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsActive
}

// GetIsActiveOk returns a tuple with the IsActive field value
// and a boolean to check if the value has been set.
func (o *PrivateLink) GetIsActiveOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsActive, true
}

// SetIsActive sets field value
func (o *PrivateLink) SetIsActive(v bool) {
	o.IsActive = v
}

func (o PrivateLink) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PrivateLink) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["expires_date"] = o.ExpiresDate
	toSerialize["html_location"] = o.HtmlLocation
	toSerialize["id"] = o.Id
	toSerialize["is_active"] = o.IsActive
	return toSerialize, nil
}

func (o *PrivateLink) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"expires_date",
		"html_location",
		"id",
		"is_active",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPrivateLink := _PrivateLink{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPrivateLink)

	if err != nil {
		return err
	}

	*o = PrivateLink(varPrivateLink)

	return err
}

type NullablePrivateLink struct {
	value *PrivateLink
	isSet bool
}

func (v NullablePrivateLink) Get() *PrivateLink {
	return v.value
}

func (v *NullablePrivateLink) Set(val *PrivateLink) {
	v.value = val
	v.isSet = true
}

func (v NullablePrivateLink) IsSet() bool {
	return v.isSet
}

func (v *NullablePrivateLink) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePrivateLink(val *PrivateLink) *NullablePrivateLink {
	return &NullablePrivateLink{value: val, isSet: true}
}

func (v NullablePrivateLink) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePrivateLink) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


