/*
 * Figshare API
 *
 * Figshare apiv2. Using Swagger 2.0
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type CreateOAuthToken struct {
	ClientId string `json:"client_id"`
	ClientSecret string `json:"client_secret"`
	// Required if grant_type is 'authorization_code'
	Code string `json:"code,omitempty"`
	GrantType string `json:"grant_type"`
	// Required if grant_type is 'password'
	Password string `json:"password,omitempty"`
	// Required if grant_type is 'refresh_token'
	RefreshToken string `json:"refresh_token,omitempty"`
	// Required if grant_type is 'password'
	Username string `json:"username,omitempty"`
}
