/*
 * Figshare API
 *
 * Figshare apiv2. Using Swagger 2.0
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Resource struct {
	// DOI of resource item
	Doi string `json:"doi,omitempty"`
	// ID of resource item
	Id string `json:"id,omitempty"`
	// Link of resource item
	Link string `json:"link,omitempty"`
	// Status of resource item
	Status string `json:"status,omitempty"`
	// Title of resource item
	Title string `json:"title,omitempty"`
	// Version of resource item
	Version int64 `json:"version,omitempty"`
}
