/*
 * Figshare API
 *
 * Figshare apiv2. Using Swagger 2.0
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type CollectionPrivateLinkCreator struct {
	// Date when this private link should expire - optional. By default private links expire in 365 days.
	ExpiresDate string `json:"expires_date,omitempty"`
}
