/*
 * Figshare API
 *
 * Figshare apiv2. Using Swagger 2.0
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type LocationWarningsUpdate struct {
	// Url for entity
	Location string `json:"location"`
	// Issues encountered during the operation
	Warnings []string `json:"warnings"`
}
