/*
 * Figshare API
 *
 * Figshare apiv2. Using Swagger 2.0
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ShortCustomField struct {
	// Custom field type
	FieldType string `json:"field_type"`
	// Custom field id
	Id int64 `json:"id"`
	// Whether the field is mandatory or not
	IsMandatory bool `json:"is_mandatory,omitempty"`
	// Custom field name
	Name string `json:"name"`
	// Order of the field in the group
	Order int64 `json:"order,omitempty"`
	// Settings for the custom field
	Settings *interface{} `json:"settings,omitempty"`
}
