/*
 * Figshare API
 *
 * Figshare apiv2. Using Swagger 2.0
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type CustomArticleField struct {
	// Custom field type
	FieldType string `json:"field_type"`
	// Whether the field is mandatory or not
	IsMandatory bool `json:"is_mandatory"`
	// Custom  metadata name
	Name string `json:"name"`
	// Order of the custom field
	Order int64 `json:"order"`
	// Settings for the custom field
	Settings *interface{} `json:"settings"`
	// Custom metadata value (can be either a string or an array of strings)
	Value *interface{} `json:"value"`
}
