/*
 * Figshare API
 *
 * Figshare apiv2. Using Swagger 2.0
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Category struct {
	// Category id
	Id int64 `json:"id"`
	// Parent category
	ParentId int64 `json:"parent_id"`
	// Path to all ancestor ids
	Path string `json:"path"`
	// ID in original standard taxonomy
	SourceId string `json:"source_id"`
	// Internal id of taxonomy the category is part of
	TaxonomyId int64 `json:"taxonomy_id"`
	// Category title
	Title string `json:"title"`
}
