/*
Figshare API

Figshare apiv2. Using Swagger 2.0

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PrivateLinkResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PrivateLinkResponse{}

// PrivateLinkResponse struct for PrivateLinkResponse
type PrivateLinkResponse struct {
	// HTML url for private link
	HtmlLocation string `json:"html_location"`
	// Url for private link
	Location string `json:"location"`
	// Token for private link
	Token string `json:"token"`
}

type _PrivateLinkResponse PrivateLinkResponse

// NewPrivateLinkResponse instantiates a new PrivateLinkResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPrivateLinkResponse(htmlLocation string, location string, token string) *PrivateLinkResponse {
	this := PrivateLinkResponse{}
	this.HtmlLocation = htmlLocation
	this.Location = location
	this.Token = token
	return &this
}

// NewPrivateLinkResponseWithDefaults instantiates a new PrivateLinkResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPrivateLinkResponseWithDefaults() *PrivateLinkResponse {
	this := PrivateLinkResponse{}
	return &this
}

// GetHtmlLocation returns the HtmlLocation field value
func (o *PrivateLinkResponse) GetHtmlLocation() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.HtmlLocation
}

// GetHtmlLocationOk returns a tuple with the HtmlLocation field value
// and a boolean to check if the value has been set.
func (o *PrivateLinkResponse) GetHtmlLocationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HtmlLocation, true
}

// SetHtmlLocation sets field value
func (o *PrivateLinkResponse) SetHtmlLocation(v string) {
	o.HtmlLocation = v
}

// GetLocation returns the Location field value
func (o *PrivateLinkResponse) GetLocation() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Location
}

// GetLocationOk returns a tuple with the Location field value
// and a boolean to check if the value has been set.
func (o *PrivateLinkResponse) GetLocationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Location, true
}

// SetLocation sets field value
func (o *PrivateLinkResponse) SetLocation(v string) {
	o.Location = v
}

// GetToken returns the Token field value
func (o *PrivateLinkResponse) GetToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *PrivateLinkResponse) GetTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *PrivateLinkResponse) SetToken(v string) {
	o.Token = v
}

func (o PrivateLinkResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PrivateLinkResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["html_location"] = o.HtmlLocation
	toSerialize["location"] = o.Location
	toSerialize["token"] = o.Token
	return toSerialize, nil
}

func (o *PrivateLinkResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"html_location",
		"location",
		"token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPrivateLinkResponse := _PrivateLinkResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPrivateLinkResponse)

	if err != nil {
		return err
	}

	*o = PrivateLinkResponse(varPrivateLinkResponse)

	return err
}

type NullablePrivateLinkResponse struct {
	value *PrivateLinkResponse
	isSet bool
}

func (v NullablePrivateLinkResponse) Get() *PrivateLinkResponse {
	return v.value
}

func (v *NullablePrivateLinkResponse) Set(val *PrivateLinkResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePrivateLinkResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePrivateLinkResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePrivateLinkResponse(val *PrivateLinkResponse) *NullablePrivateLinkResponse {
	return &NullablePrivateLinkResponse{value: val, isSet: true}
}

func (v NullablePrivateLinkResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePrivateLinkResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


