/*
Figshare API

Figshare apiv2. Using Swagger 2.0

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ProjectNoteCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectNoteCreate{}

// ProjectNoteCreate struct for ProjectNoteCreate
type ProjectNoteCreate struct {
	// Text of the note
	Text string `json:"text"`
}

type _ProjectNoteCreate ProjectNoteCreate

// NewProjectNoteCreate instantiates a new ProjectNoteCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectNoteCreate(text string) *ProjectNoteCreate {
	this := ProjectNoteCreate{}
	this.Text = text
	return &this
}

// NewProjectNoteCreateWithDefaults instantiates a new ProjectNoteCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectNoteCreateWithDefaults() *ProjectNoteCreate {
	this := ProjectNoteCreate{}
	return &this
}

// GetText returns the Text field value
func (o *ProjectNoteCreate) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *ProjectNoteCreate) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *ProjectNoteCreate) SetText(v string) {
	o.Text = v
}

func (o ProjectNoteCreate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectNoteCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["text"] = o.Text
	return toSerialize, nil
}

func (o *ProjectNoteCreate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"text",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProjectNoteCreate := _ProjectNoteCreate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProjectNoteCreate)

	if err != nil {
		return err
	}

	*o = ProjectNoteCreate(varProjectNoteCreate)

	return err
}

type NullableProjectNoteCreate struct {
	value *ProjectNoteCreate
	isSet bool
}

func (v NullableProjectNoteCreate) Get() *ProjectNoteCreate {
	return v.value
}

func (v *NullableProjectNoteCreate) Set(val *ProjectNoteCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectNoteCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectNoteCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectNoteCreate(val *ProjectNoteCreate) *NullableProjectNoteCreate {
	return &NullableProjectNoteCreate{value: val, isSet: true}
}

func (v NullableProjectNoteCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectNoteCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


