/*
Figshare API

Figshare apiv2. Using Swagger 2.0

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PrivateProjectArticle type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PrivateProjectArticle{}

// PrivateProjectArticle struct for PrivateProjectArticle
type PrivateProjectArticle struct {
	// ID of the account owning the article
	AccountId int64 `json:"account_id"`
	// List of authors
	Authors []Author `json:"authors"`
	// Curation status of the article
	CurationStatus string `json:"curation_status"`
	// List of custom fields values
	CustomFields []CustomArticleField `json:"custom_fields"`
	// If true, downloading of files for this article is disabled
	DownloadDisabled bool `json:"download_disabled"`
	// List of embargo options
	EmbargoOptions []GroupEmbargoOptions `json:"embargo_options"`
	// Article public url
	FigshareUrl string `json:"figshare_url"`
	// List of up to 10 article files.
	Files []PublicFile `json:"files"`
	// List of categories selected for the article
	Categories []Category `json:"categories"`
	// Article citation
	Citation string `json:"citation"`
	// Confidentiality reason
	ConfidentialReason string `json:"confidential_reason"`
	// Date when article was created
	CreatedDate string `json:"created_date"`
	// Article description
	Description string `json:"description"`
	// Reason for embargo
	EmbargoReason string `json:"embargo_reason"`
	// Title for embargo
	EmbargoTitle string `json:"embargo_title"`
	// Article funding
	Funding string `json:"funding"`
	// Full Article funding information
	FundingList []FundingInformation `json:"funding_list"`
	// True if any files are linked to the article
	HasLinkedFile bool `json:"has_linked_file"`
	// Article Confidentiality
	IsConfidential bool `json:"is_confidential"`
	// True if article is embargoed
	IsEmbargoed bool `json:"is_embargoed"`
	// True if article has no files
	IsMetadataRecord bool `json:"is_metadata_record"`
	// True if article is published
	IsPublic bool `json:"is_public"`
	// List of article keywords. Tags can be used instead
	Keywords []string `json:"keywords"`
	License License `json:"license"`
	// Article metadata reason
	MetadataReason string `json:"metadata_reason"`
	// List of references
	References []string `json:"references"`
	// List of related materials; supersedes references and resource DOI/title.
	RelatedMaterials []RelatedMaterial `json:"related_materials,omitempty"`
	// Article size
	Size int64 `json:"size"`
	// Article status
	Status string `json:"status"`
	// List of article tags. Keywords can be used instead
	Tags []string `json:"tags"`
	// Article version
	Version int64 `json:"version"`
	// Type of article identifier
	DefinedType int64 `json:"defined_type"`
	// Name of the article type identifier
	DefinedTypeName string `json:"defined_type_name"`
	// DOI
	Doi string `json:"doi"`
	// Handle
	Handle string `json:"handle"`
	// Unique identifier for article
	Id int64 `json:"id"`
	// Deprecated by related materials. Not applicable to regular users. In a publisher case, this is the publisher article DOI.
	ResourceDoi string `json:"resource_doi"`
	// Deprecated by related materials. Not applicable to regular users. In a publisher case, this is the publisher article title.
	ResourceTitle string `json:"resource_title"`
	// Thumbnail image
	Thumb string `json:"thumb"`
	Timeline Timeline `json:"timeline"`
	// Title of article
	Title string `json:"title"`
	// Api endpoint for article
	Url string `json:"url"`
	// Private Api endpoint for article
	UrlPrivateApi string `json:"url_private_api"`
	// Private site endpoint for article
	UrlPrivateHtml string `json:"url_private_html"`
	// Public Api endpoint for article
	UrlPublicApi string `json:"url_public_api"`
	// Public site endpoint for article
	UrlPublicHtml string `json:"url_public_html"`
}

type _PrivateProjectArticle PrivateProjectArticle

// NewPrivateProjectArticle instantiates a new PrivateProjectArticle object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPrivateProjectArticle(accountId int64, authors []Author, curationStatus string, customFields []CustomArticleField, downloadDisabled bool, embargoOptions []GroupEmbargoOptions, figshareUrl string, files []PublicFile, categories []Category, citation string, confidentialReason string, createdDate string, description string, embargoReason string, embargoTitle string, funding string, fundingList []FundingInformation, hasLinkedFile bool, isConfidential bool, isEmbargoed bool, isMetadataRecord bool, isPublic bool, keywords []string, license License, metadataReason string, references []string, size int64, status string, tags []string, version int64, definedType int64, definedTypeName string, doi string, handle string, id int64, resourceDoi string, resourceTitle string, thumb string, timeline Timeline, title string, url string, urlPrivateApi string, urlPrivateHtml string, urlPublicApi string, urlPublicHtml string) *PrivateProjectArticle {
	this := PrivateProjectArticle{}
	this.Categories = categories
	this.Citation = citation
	this.ConfidentialReason = confidentialReason
	this.CreatedDate = createdDate
	this.Description = description
	this.EmbargoReason = embargoReason
	this.EmbargoTitle = embargoTitle
	this.Funding = funding
	this.FundingList = fundingList
	this.HasLinkedFile = hasLinkedFile
	this.IsConfidential = isConfidential
	this.IsEmbargoed = isEmbargoed
	this.IsMetadataRecord = isMetadataRecord
	this.IsPublic = isPublic
	this.Keywords = keywords
	this.License = license
	this.MetadataReason = metadataReason
	this.References = references
	this.Size = size
	this.Status = status
	this.Tags = tags
	this.Version = version
	this.DefinedType = definedType
	this.DefinedTypeName = definedTypeName
	this.Doi = doi
	this.Handle = handle
	this.Id = id
	this.ResourceDoi = resourceDoi
	this.ResourceTitle = resourceTitle
	this.Thumb = thumb
	this.Timeline = timeline
	this.Title = title
	this.Url = url
	this.UrlPrivateApi = urlPrivateApi
	this.UrlPrivateHtml = urlPrivateHtml
	this.UrlPublicApi = urlPublicApi
	this.UrlPublicHtml = urlPublicHtml
	return &this
}

// NewPrivateProjectArticleWithDefaults instantiates a new PrivateProjectArticle object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPrivateProjectArticleWithDefaults() *PrivateProjectArticle {
	this := PrivateProjectArticle{}
	var resourceDoi string = ""
	this.ResourceDoi = resourceDoi
	var resourceTitle string = ""
	this.ResourceTitle = resourceTitle
	return &this
}

// GetAccountId returns the AccountId field value
func (o *PrivateProjectArticle) GetAccountId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *PrivateProjectArticle) GetAccountIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *PrivateProjectArticle) SetAccountId(v int64) {
	o.AccountId = v
}

// GetAuthors returns the Authors field value
func (o *PrivateProjectArticle) GetAuthors() []Author {
	if o == nil {
		var ret []Author
		return ret
	}

	return o.Authors
}

// GetAuthorsOk returns a tuple with the Authors field value
// and a boolean to check if the value has been set.
func (o *PrivateProjectArticle) GetAuthorsOk() ([]Author, bool) {
	if o == nil {
		return nil, false
	}
	return o.Authors, true
}

// SetAuthors sets field value
func (o *PrivateProjectArticle) SetAuthors(v []Author) {
	o.Authors = v
}

// GetCurationStatus returns the CurationStatus field value
func (o *PrivateProjectArticle) GetCurationStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CurationStatus
}

// GetCurationStatusOk returns a tuple with the CurationStatus field value
// and a boolean to check if the value has been set.
func (o *PrivateProjectArticle) GetCurationStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CurationStatus, true
}

// SetCurationStatus sets field value
func (o *PrivateProjectArticle) SetCurationStatus(v string) {
	o.CurationStatus = v
}

// GetCustomFields returns the CustomFields field value
func (o *PrivateProjectArticle) GetCustomFields() []CustomArticleField {
	if o == nil {
		var ret []CustomArticleField
		return ret
	}

	return o.CustomFields
}

// GetCustomFieldsOk returns a tuple with the CustomFields field value
// and a boolean to check if the value has been set.
func (o *PrivateProjectArticle) GetCustomFieldsOk() ([]CustomArticleField, bool) {
	if o == nil {
		return nil, false
	}
	return o.CustomFields, true
}

// SetCustomFields sets field value
func (o *PrivateProjectArticle) SetCustomFields(v []CustomArticleField) {
	o.CustomFields = v
}

// GetDownloadDisabled returns the DownloadDisabled field value
func (o *PrivateProjectArticle) GetDownloadDisabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.DownloadDisabled
}

// GetDownloadDisabledOk returns a tuple with the DownloadDisabled field value
// and a boolean to check if the value has been set.
func (o *PrivateProjectArticle) GetDownloadDisabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DownloadDisabled, true
}

// SetDownloadDisabled sets field value
func (o *PrivateProjectArticle) SetDownloadDisabled(v bool) {
	o.DownloadDisabled = v
}

// GetEmbargoOptions returns the EmbargoOptions field value
func (o *PrivateProjectArticle) GetEmbargoOptions() []GroupEmbargoOptions {
	if o == nil {
		var ret []GroupEmbargoOptions
		return ret
	}

	return o.EmbargoOptions
}

// GetEmbargoOptionsOk returns a tuple with the EmbargoOptions field value
// and a boolean to check if the value has been set.
func (o *PrivateProjectArticle) GetEmbargoOptionsOk() ([]GroupEmbargoOptions, bool) {
	if o == nil {
		return nil, false
	}
	return o.EmbargoOptions, true
}

// SetEmbargoOptions sets field value
func (o *PrivateProjectArticle) SetEmbargoOptions(v []GroupEmbargoOptions) {
	o.EmbargoOptions = v
}

// GetFigshareUrl returns the FigshareUrl field value
func (o *PrivateProjectArticle) GetFigshareUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FigshareUrl
}

// GetFigshareUrlOk returns a tuple with the FigshareUrl field value
// and a boolean to check if the value has been set.
func (o *PrivateProjectArticle) GetFigshareUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FigshareUrl, true
}

// SetFigshareUrl sets field value
func (o *PrivateProjectArticle) SetFigshareUrl(v string) {
	o.FigshareUrl = v
}

// GetFiles returns the Files field value
func (o *PrivateProjectArticle) GetFiles() []PublicFile {
	if o == nil {
		var ret []PublicFile
		return ret
	}

	return o.Files
}

// GetFilesOk returns a tuple with the Files field value
// and a boolean to check if the value has been set.
func (o *PrivateProjectArticle) GetFilesOk() ([]PublicFile, bool) {
	if o == nil {
		return nil, false
	}
	return o.Files, true
}

// SetFiles sets field value
func (o *PrivateProjectArticle) SetFiles(v []PublicFile) {
	o.Files = v
}

// GetCategories returns the Categories field value
func (o *PrivateProjectArticle) GetCategories() []Category {
	if o == nil {
		var ret []Category
		return ret
	}

	return o.Categories
}

// GetCategoriesOk returns a tuple with the Categories field value
// and a boolean to check if the value has been set.
func (o *PrivateProjectArticle) GetCategoriesOk() ([]Category, bool) {
	if o == nil {
		return nil, false
	}
	return o.Categories, true
}

// SetCategories sets field value
func (o *PrivateProjectArticle) SetCategories(v []Category) {
	o.Categories = v
}

// GetCitation returns the Citation field value
func (o *PrivateProjectArticle) GetCitation() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Citation
}

// GetCitationOk returns a tuple with the Citation field value
// and a boolean to check if the value has been set.
func (o *PrivateProjectArticle) GetCitationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Citation, true
}

// SetCitation sets field value
func (o *PrivateProjectArticle) SetCitation(v string) {
	o.Citation = v
}

// GetConfidentialReason returns the ConfidentialReason field value
func (o *PrivateProjectArticle) GetConfidentialReason() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConfidentialReason
}

// GetConfidentialReasonOk returns a tuple with the ConfidentialReason field value
// and a boolean to check if the value has been set.
func (o *PrivateProjectArticle) GetConfidentialReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConfidentialReason, true
}

// SetConfidentialReason sets field value
func (o *PrivateProjectArticle) SetConfidentialReason(v string) {
	o.ConfidentialReason = v
}

// GetCreatedDate returns the CreatedDate field value
func (o *PrivateProjectArticle) GetCreatedDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedDate
}

// GetCreatedDateOk returns a tuple with the CreatedDate field value
// and a boolean to check if the value has been set.
func (o *PrivateProjectArticle) GetCreatedDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedDate, true
}

// SetCreatedDate sets field value
func (o *PrivateProjectArticle) SetCreatedDate(v string) {
	o.CreatedDate = v
}

// GetDescription returns the Description field value
func (o *PrivateProjectArticle) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *PrivateProjectArticle) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *PrivateProjectArticle) SetDescription(v string) {
	o.Description = v
}

// GetEmbargoReason returns the EmbargoReason field value
func (o *PrivateProjectArticle) GetEmbargoReason() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EmbargoReason
}

// GetEmbargoReasonOk returns a tuple with the EmbargoReason field value
// and a boolean to check if the value has been set.
func (o *PrivateProjectArticle) GetEmbargoReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EmbargoReason, true
}

// SetEmbargoReason sets field value
func (o *PrivateProjectArticle) SetEmbargoReason(v string) {
	o.EmbargoReason = v
}

// GetEmbargoTitle returns the EmbargoTitle field value
func (o *PrivateProjectArticle) GetEmbargoTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EmbargoTitle
}

// GetEmbargoTitleOk returns a tuple with the EmbargoTitle field value
// and a boolean to check if the value has been set.
func (o *PrivateProjectArticle) GetEmbargoTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EmbargoTitle, true
}

// SetEmbargoTitle sets field value
func (o *PrivateProjectArticle) SetEmbargoTitle(v string) {
	o.EmbargoTitle = v
}

// GetFunding returns the Funding field value
func (o *PrivateProjectArticle) GetFunding() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Funding
}

// GetFundingOk returns a tuple with the Funding field value
// and a boolean to check if the value has been set.
func (o *PrivateProjectArticle) GetFundingOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Funding, true
}

// SetFunding sets field value
func (o *PrivateProjectArticle) SetFunding(v string) {
	o.Funding = v
}

// GetFundingList returns the FundingList field value
func (o *PrivateProjectArticle) GetFundingList() []FundingInformation {
	if o == nil {
		var ret []FundingInformation
		return ret
	}

	return o.FundingList
}

// GetFundingListOk returns a tuple with the FundingList field value
// and a boolean to check if the value has been set.
func (o *PrivateProjectArticle) GetFundingListOk() ([]FundingInformation, bool) {
	if o == nil {
		return nil, false
	}
	return o.FundingList, true
}

// SetFundingList sets field value
func (o *PrivateProjectArticle) SetFundingList(v []FundingInformation) {
	o.FundingList = v
}

// GetHasLinkedFile returns the HasLinkedFile field value
func (o *PrivateProjectArticle) GetHasLinkedFile() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasLinkedFile
}

// GetHasLinkedFileOk returns a tuple with the HasLinkedFile field value
// and a boolean to check if the value has been set.
func (o *PrivateProjectArticle) GetHasLinkedFileOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasLinkedFile, true
}

// SetHasLinkedFile sets field value
func (o *PrivateProjectArticle) SetHasLinkedFile(v bool) {
	o.HasLinkedFile = v
}

// GetIsConfidential returns the IsConfidential field value
func (o *PrivateProjectArticle) GetIsConfidential() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsConfidential
}

// GetIsConfidentialOk returns a tuple with the IsConfidential field value
// and a boolean to check if the value has been set.
func (o *PrivateProjectArticle) GetIsConfidentialOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsConfidential, true
}

// SetIsConfidential sets field value
func (o *PrivateProjectArticle) SetIsConfidential(v bool) {
	o.IsConfidential = v
}

// GetIsEmbargoed returns the IsEmbargoed field value
func (o *PrivateProjectArticle) GetIsEmbargoed() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsEmbargoed
}

// GetIsEmbargoedOk returns a tuple with the IsEmbargoed field value
// and a boolean to check if the value has been set.
func (o *PrivateProjectArticle) GetIsEmbargoedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsEmbargoed, true
}

// SetIsEmbargoed sets field value
func (o *PrivateProjectArticle) SetIsEmbargoed(v bool) {
	o.IsEmbargoed = v
}

// GetIsMetadataRecord returns the IsMetadataRecord field value
func (o *PrivateProjectArticle) GetIsMetadataRecord() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsMetadataRecord
}

// GetIsMetadataRecordOk returns a tuple with the IsMetadataRecord field value
// and a boolean to check if the value has been set.
func (o *PrivateProjectArticle) GetIsMetadataRecordOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsMetadataRecord, true
}

// SetIsMetadataRecord sets field value
func (o *PrivateProjectArticle) SetIsMetadataRecord(v bool) {
	o.IsMetadataRecord = v
}

// GetIsPublic returns the IsPublic field value
func (o *PrivateProjectArticle) GetIsPublic() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsPublic
}

// GetIsPublicOk returns a tuple with the IsPublic field value
// and a boolean to check if the value has been set.
func (o *PrivateProjectArticle) GetIsPublicOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsPublic, true
}

// SetIsPublic sets field value
func (o *PrivateProjectArticle) SetIsPublic(v bool) {
	o.IsPublic = v
}

// GetKeywords returns the Keywords field value
func (o *PrivateProjectArticle) GetKeywords() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Keywords
}

// GetKeywordsOk returns a tuple with the Keywords field value
// and a boolean to check if the value has been set.
func (o *PrivateProjectArticle) GetKeywordsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Keywords, true
}

// SetKeywords sets field value
func (o *PrivateProjectArticle) SetKeywords(v []string) {
	o.Keywords = v
}

// GetLicense returns the License field value
func (o *PrivateProjectArticle) GetLicense() License {
	if o == nil {
		var ret License
		return ret
	}

	return o.License
}

// GetLicenseOk returns a tuple with the License field value
// and a boolean to check if the value has been set.
func (o *PrivateProjectArticle) GetLicenseOk() (*License, bool) {
	if o == nil {
		return nil, false
	}
	return &o.License, true
}

// SetLicense sets field value
func (o *PrivateProjectArticle) SetLicense(v License) {
	o.License = v
}

// GetMetadataReason returns the MetadataReason field value
func (o *PrivateProjectArticle) GetMetadataReason() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MetadataReason
}

// GetMetadataReasonOk returns a tuple with the MetadataReason field value
// and a boolean to check if the value has been set.
func (o *PrivateProjectArticle) GetMetadataReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MetadataReason, true
}

// SetMetadataReason sets field value
func (o *PrivateProjectArticle) SetMetadataReason(v string) {
	o.MetadataReason = v
}

// GetReferences returns the References field value
func (o *PrivateProjectArticle) GetReferences() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.References
}

// GetReferencesOk returns a tuple with the References field value
// and a boolean to check if the value has been set.
func (o *PrivateProjectArticle) GetReferencesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.References, true
}

// SetReferences sets field value
func (o *PrivateProjectArticle) SetReferences(v []string) {
	o.References = v
}

// GetRelatedMaterials returns the RelatedMaterials field value if set, zero value otherwise.
func (o *PrivateProjectArticle) GetRelatedMaterials() []RelatedMaterial {
	if o == nil || IsNil(o.RelatedMaterials) {
		var ret []RelatedMaterial
		return ret
	}
	return o.RelatedMaterials
}

// GetRelatedMaterialsOk returns a tuple with the RelatedMaterials field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrivateProjectArticle) GetRelatedMaterialsOk() ([]RelatedMaterial, bool) {
	if o == nil || IsNil(o.RelatedMaterials) {
		return nil, false
	}
	return o.RelatedMaterials, true
}

// HasRelatedMaterials returns a boolean if a field has been set.
func (o *PrivateProjectArticle) HasRelatedMaterials() bool {
	if o != nil && !IsNil(o.RelatedMaterials) {
		return true
	}

	return false
}

// SetRelatedMaterials gets a reference to the given []RelatedMaterial and assigns it to the RelatedMaterials field.
func (o *PrivateProjectArticle) SetRelatedMaterials(v []RelatedMaterial) {
	o.RelatedMaterials = v
}

// GetSize returns the Size field value
func (o *PrivateProjectArticle) GetSize() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Size
}

// GetSizeOk returns a tuple with the Size field value
// and a boolean to check if the value has been set.
func (o *PrivateProjectArticle) GetSizeOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Size, true
}

// SetSize sets field value
func (o *PrivateProjectArticle) SetSize(v int64) {
	o.Size = v
}

// GetStatus returns the Status field value
func (o *PrivateProjectArticle) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *PrivateProjectArticle) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *PrivateProjectArticle) SetStatus(v string) {
	o.Status = v
}

// GetTags returns the Tags field value
func (o *PrivateProjectArticle) GetTags() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value
// and a boolean to check if the value has been set.
func (o *PrivateProjectArticle) GetTagsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tags, true
}

// SetTags sets field value
func (o *PrivateProjectArticle) SetTags(v []string) {
	o.Tags = v
}

// GetVersion returns the Version field value
func (o *PrivateProjectArticle) GetVersion() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *PrivateProjectArticle) GetVersionOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *PrivateProjectArticle) SetVersion(v int64) {
	o.Version = v
}

// GetDefinedType returns the DefinedType field value
func (o *PrivateProjectArticle) GetDefinedType() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.DefinedType
}

// GetDefinedTypeOk returns a tuple with the DefinedType field value
// and a boolean to check if the value has been set.
func (o *PrivateProjectArticle) GetDefinedTypeOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DefinedType, true
}

// SetDefinedType sets field value
func (o *PrivateProjectArticle) SetDefinedType(v int64) {
	o.DefinedType = v
}

// GetDefinedTypeName returns the DefinedTypeName field value
func (o *PrivateProjectArticle) GetDefinedTypeName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DefinedTypeName
}

// GetDefinedTypeNameOk returns a tuple with the DefinedTypeName field value
// and a boolean to check if the value has been set.
func (o *PrivateProjectArticle) GetDefinedTypeNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DefinedTypeName, true
}

// SetDefinedTypeName sets field value
func (o *PrivateProjectArticle) SetDefinedTypeName(v string) {
	o.DefinedTypeName = v
}

// GetDoi returns the Doi field value
func (o *PrivateProjectArticle) GetDoi() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Doi
}

// GetDoiOk returns a tuple with the Doi field value
// and a boolean to check if the value has been set.
func (o *PrivateProjectArticle) GetDoiOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Doi, true
}

// SetDoi sets field value
func (o *PrivateProjectArticle) SetDoi(v string) {
	o.Doi = v
}

// GetHandle returns the Handle field value
func (o *PrivateProjectArticle) GetHandle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Handle
}

// GetHandleOk returns a tuple with the Handle field value
// and a boolean to check if the value has been set.
func (o *PrivateProjectArticle) GetHandleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Handle, true
}

// SetHandle sets field value
func (o *PrivateProjectArticle) SetHandle(v string) {
	o.Handle = v
}

// GetId returns the Id field value
func (o *PrivateProjectArticle) GetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PrivateProjectArticle) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PrivateProjectArticle) SetId(v int64) {
	o.Id = v
}

// GetResourceDoi returns the ResourceDoi field value
func (o *PrivateProjectArticle) GetResourceDoi() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResourceDoi
}

// GetResourceDoiOk returns a tuple with the ResourceDoi field value
// and a boolean to check if the value has been set.
func (o *PrivateProjectArticle) GetResourceDoiOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResourceDoi, true
}

// SetResourceDoi sets field value
func (o *PrivateProjectArticle) SetResourceDoi(v string) {
	o.ResourceDoi = v
}

// GetResourceTitle returns the ResourceTitle field value
func (o *PrivateProjectArticle) GetResourceTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResourceTitle
}

// GetResourceTitleOk returns a tuple with the ResourceTitle field value
// and a boolean to check if the value has been set.
func (o *PrivateProjectArticle) GetResourceTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResourceTitle, true
}

// SetResourceTitle sets field value
func (o *PrivateProjectArticle) SetResourceTitle(v string) {
	o.ResourceTitle = v
}

// GetThumb returns the Thumb field value
func (o *PrivateProjectArticle) GetThumb() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Thumb
}

// GetThumbOk returns a tuple with the Thumb field value
// and a boolean to check if the value has been set.
func (o *PrivateProjectArticle) GetThumbOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Thumb, true
}

// SetThumb sets field value
func (o *PrivateProjectArticle) SetThumb(v string) {
	o.Thumb = v
}

// GetTimeline returns the Timeline field value
func (o *PrivateProjectArticle) GetTimeline() Timeline {
	if o == nil {
		var ret Timeline
		return ret
	}

	return o.Timeline
}

// GetTimelineOk returns a tuple with the Timeline field value
// and a boolean to check if the value has been set.
func (o *PrivateProjectArticle) GetTimelineOk() (*Timeline, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timeline, true
}

// SetTimeline sets field value
func (o *PrivateProjectArticle) SetTimeline(v Timeline) {
	o.Timeline = v
}

// GetTitle returns the Title field value
func (o *PrivateProjectArticle) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *PrivateProjectArticle) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *PrivateProjectArticle) SetTitle(v string) {
	o.Title = v
}

// GetUrl returns the Url field value
func (o *PrivateProjectArticle) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *PrivateProjectArticle) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *PrivateProjectArticle) SetUrl(v string) {
	o.Url = v
}

// GetUrlPrivateApi returns the UrlPrivateApi field value
func (o *PrivateProjectArticle) GetUrlPrivateApi() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UrlPrivateApi
}

// GetUrlPrivateApiOk returns a tuple with the UrlPrivateApi field value
// and a boolean to check if the value has been set.
func (o *PrivateProjectArticle) GetUrlPrivateApiOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UrlPrivateApi, true
}

// SetUrlPrivateApi sets field value
func (o *PrivateProjectArticle) SetUrlPrivateApi(v string) {
	o.UrlPrivateApi = v
}

// GetUrlPrivateHtml returns the UrlPrivateHtml field value
func (o *PrivateProjectArticle) GetUrlPrivateHtml() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UrlPrivateHtml
}

// GetUrlPrivateHtmlOk returns a tuple with the UrlPrivateHtml field value
// and a boolean to check if the value has been set.
func (o *PrivateProjectArticle) GetUrlPrivateHtmlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UrlPrivateHtml, true
}

// SetUrlPrivateHtml sets field value
func (o *PrivateProjectArticle) SetUrlPrivateHtml(v string) {
	o.UrlPrivateHtml = v
}

// GetUrlPublicApi returns the UrlPublicApi field value
func (o *PrivateProjectArticle) GetUrlPublicApi() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UrlPublicApi
}

// GetUrlPublicApiOk returns a tuple with the UrlPublicApi field value
// and a boolean to check if the value has been set.
func (o *PrivateProjectArticle) GetUrlPublicApiOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UrlPublicApi, true
}

// SetUrlPublicApi sets field value
func (o *PrivateProjectArticle) SetUrlPublicApi(v string) {
	o.UrlPublicApi = v
}

// GetUrlPublicHtml returns the UrlPublicHtml field value
func (o *PrivateProjectArticle) GetUrlPublicHtml() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UrlPublicHtml
}

// GetUrlPublicHtmlOk returns a tuple with the UrlPublicHtml field value
// and a boolean to check if the value has been set.
func (o *PrivateProjectArticle) GetUrlPublicHtmlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UrlPublicHtml, true
}

// SetUrlPublicHtml sets field value
func (o *PrivateProjectArticle) SetUrlPublicHtml(v string) {
	o.UrlPublicHtml = v
}

func (o PrivateProjectArticle) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PrivateProjectArticle) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["account_id"] = o.AccountId
	toSerialize["authors"] = o.Authors
	toSerialize["curation_status"] = o.CurationStatus
	toSerialize["custom_fields"] = o.CustomFields
	toSerialize["download_disabled"] = o.DownloadDisabled
	toSerialize["embargo_options"] = o.EmbargoOptions
	toSerialize["figshare_url"] = o.FigshareUrl
	toSerialize["files"] = o.Files
	toSerialize["categories"] = o.Categories
	toSerialize["citation"] = o.Citation
	toSerialize["confidential_reason"] = o.ConfidentialReason
	toSerialize["created_date"] = o.CreatedDate
	toSerialize["description"] = o.Description
	toSerialize["embargo_reason"] = o.EmbargoReason
	toSerialize["embargo_title"] = o.EmbargoTitle
	toSerialize["funding"] = o.Funding
	toSerialize["funding_list"] = o.FundingList
	toSerialize["has_linked_file"] = o.HasLinkedFile
	toSerialize["is_confidential"] = o.IsConfidential
	toSerialize["is_embargoed"] = o.IsEmbargoed
	toSerialize["is_metadata_record"] = o.IsMetadataRecord
	toSerialize["is_public"] = o.IsPublic
	toSerialize["keywords"] = o.Keywords
	toSerialize["license"] = o.License
	toSerialize["metadata_reason"] = o.MetadataReason
	toSerialize["references"] = o.References
	if !IsNil(o.RelatedMaterials) {
		toSerialize["related_materials"] = o.RelatedMaterials
	}
	toSerialize["size"] = o.Size
	toSerialize["status"] = o.Status
	toSerialize["tags"] = o.Tags
	toSerialize["version"] = o.Version
	toSerialize["defined_type"] = o.DefinedType
	toSerialize["defined_type_name"] = o.DefinedTypeName
	toSerialize["doi"] = o.Doi
	toSerialize["handle"] = o.Handle
	toSerialize["id"] = o.Id
	toSerialize["resource_doi"] = o.ResourceDoi
	toSerialize["resource_title"] = o.ResourceTitle
	toSerialize["thumb"] = o.Thumb
	toSerialize["timeline"] = o.Timeline
	toSerialize["title"] = o.Title
	toSerialize["url"] = o.Url
	toSerialize["url_private_api"] = o.UrlPrivateApi
	toSerialize["url_private_html"] = o.UrlPrivateHtml
	toSerialize["url_public_api"] = o.UrlPublicApi
	toSerialize["url_public_html"] = o.UrlPublicHtml
	return toSerialize, nil
}

func (o *PrivateProjectArticle) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"account_id",
		"authors",
		"curation_status",
		"custom_fields",
		"download_disabled",
		"embargo_options",
		"figshare_url",
		"files",
		"categories",
		"citation",
		"confidential_reason",
		"created_date",
		"description",
		"embargo_reason",
		"embargo_title",
		"funding",
		"funding_list",
		"has_linked_file",
		"is_confidential",
		"is_embargoed",
		"is_metadata_record",
		"is_public",
		"keywords",
		"license",
		"metadata_reason",
		"references",
		"size",
		"status",
		"tags",
		"version",
		"defined_type",
		"defined_type_name",
		"doi",
		"handle",
		"id",
		"resource_doi",
		"resource_title",
		"thumb",
		"timeline",
		"title",
		"url",
		"url_private_api",
		"url_private_html",
		"url_public_api",
		"url_public_html",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPrivateProjectArticle := _PrivateProjectArticle{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPrivateProjectArticle)

	if err != nil {
		return err
	}

	*o = PrivateProjectArticle(varPrivateProjectArticle)

	return err
}

type NullablePrivateProjectArticle struct {
	value *PrivateProjectArticle
	isSet bool
}

func (v NullablePrivateProjectArticle) Get() *PrivateProjectArticle {
	return v.value
}

func (v *NullablePrivateProjectArticle) Set(val *PrivateProjectArticle) {
	v.value = val
	v.isSet = true
}

func (v NullablePrivateProjectArticle) IsSet() bool {
	return v.isSet
}

func (v *NullablePrivateProjectArticle) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePrivateProjectArticle(val *PrivateProjectArticle) *NullablePrivateProjectArticle {
	return &NullablePrivateProjectArticle{value: val, isSet: true}
}

func (v NullablePrivateProjectArticle) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePrivateProjectArticle) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


