/*
Figshare API

Figshare apiv2. Using Swagger 2.0

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CollectionVersions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CollectionVersions{}

// CollectionVersions struct for CollectionVersions
type CollectionVersions struct {
	// Full Collection funding information
	Funding []FundingInformation `json:"funding"`
	// Api endpoint for the collection version
	Url string `json:"url"`
	// Version number
	Version int64 `json:"version"`
}

type _CollectionVersions CollectionVersions

// NewCollectionVersions instantiates a new CollectionVersions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCollectionVersions(funding []FundingInformation, url string, version int64) *CollectionVersions {
	this := CollectionVersions{}
	this.Funding = funding
	this.Url = url
	this.Version = version
	return &this
}

// NewCollectionVersionsWithDefaults instantiates a new CollectionVersions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCollectionVersionsWithDefaults() *CollectionVersions {
	this := CollectionVersions{}
	return &this
}

// GetFunding returns the Funding field value
func (o *CollectionVersions) GetFunding() []FundingInformation {
	if o == nil {
		var ret []FundingInformation
		return ret
	}

	return o.Funding
}

// GetFundingOk returns a tuple with the Funding field value
// and a boolean to check if the value has been set.
func (o *CollectionVersions) GetFundingOk() ([]FundingInformation, bool) {
	if o == nil {
		return nil, false
	}
	return o.Funding, true
}

// SetFunding sets field value
func (o *CollectionVersions) SetFunding(v []FundingInformation) {
	o.Funding = v
}

// GetUrl returns the Url field value
func (o *CollectionVersions) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *CollectionVersions) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *CollectionVersions) SetUrl(v string) {
	o.Url = v
}

// GetVersion returns the Version field value
func (o *CollectionVersions) GetVersion() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *CollectionVersions) GetVersionOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *CollectionVersions) SetVersion(v int64) {
	o.Version = v
}

func (o CollectionVersions) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CollectionVersions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["funding"] = o.Funding
	toSerialize["url"] = o.Url
	toSerialize["version"] = o.Version
	return toSerialize, nil
}

func (o *CollectionVersions) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"funding",
		"url",
		"version",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCollectionVersions := _CollectionVersions{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCollectionVersions)

	if err != nil {
		return err
	}

	*o = CollectionVersions(varCollectionVersions)

	return err
}

type NullableCollectionVersions struct {
	value *CollectionVersions
	isSet bool
}

func (v NullableCollectionVersions) Get() *CollectionVersions {
	return v.value
}

func (v *NullableCollectionVersions) Set(val *CollectionVersions) {
	v.value = val
	v.isSet = true
}

func (v NullableCollectionVersions) IsSet() bool {
	return v.isSet
}

func (v *NullableCollectionVersions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCollectionVersions(val *CollectionVersions) *NullableCollectionVersions {
	return &NullableCollectionVersions{value: val, isSet: true}
}

func (v NullableCollectionVersions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCollectionVersions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


