/*
 * Figshare API
 *
 * Figshare apiv2. Using Swagger 2.0
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Article struct {
	// Date when article was created
	CreatedDate string `json:"created_date"`
	// Type of article identifier
	DefinedType int64 `json:"defined_type"`
	// Name of the article type identifier
	DefinedTypeName string `json:"defined_type_name"`
	// DOI
	Doi string `json:"doi"`
	// Handle
	Handle string `json:"handle"`
	// Unique identifier for article
	Id int64 `json:"id"`
	// Deprecated by related materials. Not applicable to regular users. In a publisher case, this is the publisher article DOI.
	ResourceDoi string `json:"resource_doi"`
	// Deprecated by related materials. Not applicable to regular users. In a publisher case, this is the publisher article title.
	ResourceTitle string `json:"resource_title"`
	// Thumbnail image
	Thumb string `json:"thumb"`
	// Various timeline dates
	Timeline *Timeline `json:"timeline"`
	// Title of article
	Title string `json:"title"`
	// Api endpoint for article
	Url string `json:"url"`
	// Private Api endpoint for article
	UrlPrivateApi string `json:"url_private_api"`
	// Private site endpoint for article
	UrlPrivateHtml string `json:"url_private_html"`
	// Public Api endpoint for article
	UrlPublicApi string `json:"url_public_api"`
	// Public site endpoint for article
	UrlPublicHtml string `json:"url_public_html"`
}
