/*
 * Figshare API
 *
 * Figshare apiv2. Using Swagger 2.0
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ProjectNotePrivate struct {
	// Note Abstract - short/truncated content
	Abstract string `json:"abstract"`
	// Date when note was created
	CreatedDate string `json:"created_date"`
	// Project note id
	Id int64 `json:"id"`
	// Date when note was last modified
	ModifiedDate string `json:"modified_date"`
	// User who wrote the note
	UserId int64 `json:"user_id"`
	// Username of the one who wrote the note
	UserName string `json:"user_name"`
	// Full text of note
	Text string `json:"text,omitempty"`
}
