/*
Figshare API

Testing InstitutionsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_InstitutionsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test InstitutionsAPIService AccountInstitutionCuration", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var curationId int64

		resp, httpRes, err := apiClient.InstitutionsAPI.AccountInstitutionCuration(context.Background(), curationId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InstitutionsAPIService AccountInstitutionCurations", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.InstitutionsAPI.AccountInstitutionCurations(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InstitutionsAPIService CustomFieldsList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.InstitutionsAPI.CustomFieldsList(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InstitutionsAPIService CustomFieldsUpload", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var customFieldId int64

		resp, httpRes, err := apiClient.InstitutionsAPI.CustomFieldsUpload(context.Background(), customFieldId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InstitutionsAPIService GetAccountInstitutionCurationComments", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var curationId int64

		resp, httpRes, err := apiClient.InstitutionsAPI.GetAccountInstitutionCurationComments(context.Background(), curationId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InstitutionsAPIService InstitutionArticles", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var institutionStringId string

		resp, httpRes, err := apiClient.InstitutionsAPI.InstitutionArticles(context.Background(), institutionStringId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InstitutionsAPIService InstitutionHrfeedUpload", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.InstitutionsAPI.InstitutionHrfeedUpload(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InstitutionsAPIService PostAccountInstitutionCurationComments", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var curationId int64

		httpRes, err := apiClient.InstitutionsAPI.PostAccountInstitutionCurationComments(context.Background(), curationId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InstitutionsAPIService PrivateAccountInstitutionUser", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var accountId int64

		resp, httpRes, err := apiClient.InstitutionsAPI.PrivateAccountInstitutionUser(context.Background(), accountId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InstitutionsAPIService PrivateCategoriesList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.InstitutionsAPI.PrivateCategoriesList(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InstitutionsAPIService PrivateGroupEmbargoOptionsDetails", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var groupId int64

		resp, httpRes, err := apiClient.InstitutionsAPI.PrivateGroupEmbargoOptionsDetails(context.Background(), groupId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InstitutionsAPIService PrivateInstitutionAccount", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var accountId int64

		resp, httpRes, err := apiClient.InstitutionsAPI.PrivateInstitutionAccount(context.Background(), accountId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InstitutionsAPIService PrivateInstitutionAccountGroupRoleDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var accountId int64
		var groupId int64
		var roleId int64

		httpRes, err := apiClient.InstitutionsAPI.PrivateInstitutionAccountGroupRoleDelete(context.Background(), accountId, groupId, roleId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InstitutionsAPIService PrivateInstitutionAccountGroupRoles", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var accountId int64

		resp, httpRes, err := apiClient.InstitutionsAPI.PrivateInstitutionAccountGroupRoles(context.Background(), accountId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InstitutionsAPIService PrivateInstitutionAccountGroupRolesCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var accountId int64

		httpRes, err := apiClient.InstitutionsAPI.PrivateInstitutionAccountGroupRolesCreate(context.Background(), accountId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InstitutionsAPIService PrivateInstitutionAccountsCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.InstitutionsAPI.PrivateInstitutionAccountsCreate(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InstitutionsAPIService PrivateInstitutionAccountsList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.InstitutionsAPI.PrivateInstitutionAccountsList(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InstitutionsAPIService PrivateInstitutionAccountsSearch", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.InstitutionsAPI.PrivateInstitutionAccountsSearch(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InstitutionsAPIService PrivateInstitutionAccountsUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var accountId int64

		httpRes, err := apiClient.InstitutionsAPI.PrivateInstitutionAccountsUpdate(context.Background(), accountId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InstitutionsAPIService PrivateInstitutionArticles", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.InstitutionsAPI.PrivateInstitutionArticles(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InstitutionsAPIService PrivateInstitutionDetails", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.InstitutionsAPI.PrivateInstitutionDetails(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InstitutionsAPIService PrivateInstitutionEmbargoOptionsDetails", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.InstitutionsAPI.PrivateInstitutionEmbargoOptionsDetails(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InstitutionsAPIService PrivateInstitutionGroupsList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.InstitutionsAPI.PrivateInstitutionGroupsList(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InstitutionsAPIService PrivateInstitutionRolesList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.InstitutionsAPI.PrivateInstitutionRolesList(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
