/*
Figshare API

Testing ProjectsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_ProjectsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ProjectsAPIService PrivateProjectArticleDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId int64
		var articleId int64

		httpRes, err := apiClient.ProjectsAPI.PrivateProjectArticleDelete(context.Background(), projectId, articleId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProjectsAPIService PrivateProjectArticleDetails", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId int64
		var articleId int64

		resp, httpRes, err := apiClient.ProjectsAPI.PrivateProjectArticleDetails(context.Background(), projectId, articleId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProjectsAPIService PrivateProjectArticleFile", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId int64
		var articleId int64
		var fileId int64

		resp, httpRes, err := apiClient.ProjectsAPI.PrivateProjectArticleFile(context.Background(), projectId, articleId, fileId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProjectsAPIService PrivateProjectArticleFiles", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId int64
		var articleId int64

		resp, httpRes, err := apiClient.ProjectsAPI.PrivateProjectArticleFiles(context.Background(), projectId, articleId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProjectsAPIService PrivateProjectArticlesCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId int64

		resp, httpRes, err := apiClient.ProjectsAPI.PrivateProjectArticlesCreate(context.Background(), projectId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProjectsAPIService PrivateProjectArticlesList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId int64

		resp, httpRes, err := apiClient.ProjectsAPI.PrivateProjectArticlesList(context.Background(), projectId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProjectsAPIService PrivateProjectCollaboratorDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId int64
		var userId int64

		httpRes, err := apiClient.ProjectsAPI.PrivateProjectCollaboratorDelete(context.Background(), projectId, userId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProjectsAPIService PrivateProjectCollaboratorsInvite", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId int64

		resp, httpRes, err := apiClient.ProjectsAPI.PrivateProjectCollaboratorsInvite(context.Background(), projectId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProjectsAPIService PrivateProjectCollaboratorsList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId int64

		resp, httpRes, err := apiClient.ProjectsAPI.PrivateProjectCollaboratorsList(context.Background(), projectId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProjectsAPIService PrivateProjectCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ProjectsAPI.PrivateProjectCreate(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProjectsAPIService PrivateProjectDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId int64

		httpRes, err := apiClient.ProjectsAPI.PrivateProjectDelete(context.Background(), projectId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProjectsAPIService PrivateProjectDetails", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId int64

		resp, httpRes, err := apiClient.ProjectsAPI.PrivateProjectDetails(context.Background(), projectId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProjectsAPIService PrivateProjectLeave", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId int64

		httpRes, err := apiClient.ProjectsAPI.PrivateProjectLeave(context.Background(), projectId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProjectsAPIService PrivateProjectNote", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId int64
		var noteId int64

		resp, httpRes, err := apiClient.ProjectsAPI.PrivateProjectNote(context.Background(), projectId, noteId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProjectsAPIService PrivateProjectNoteDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId int64
		var noteId int64

		httpRes, err := apiClient.ProjectsAPI.PrivateProjectNoteDelete(context.Background(), projectId, noteId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProjectsAPIService PrivateProjectNoteUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId int64
		var noteId int64

		httpRes, err := apiClient.ProjectsAPI.PrivateProjectNoteUpdate(context.Background(), projectId, noteId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProjectsAPIService PrivateProjectNotesCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId int64

		resp, httpRes, err := apiClient.ProjectsAPI.PrivateProjectNotesCreate(context.Background(), projectId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProjectsAPIService PrivateProjectNotesList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId int64

		resp, httpRes, err := apiClient.ProjectsAPI.PrivateProjectNotesList(context.Background(), projectId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProjectsAPIService PrivateProjectPartialUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId int64

		httpRes, err := apiClient.ProjectsAPI.PrivateProjectPartialUpdate(context.Background(), projectId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProjectsAPIService PrivateProjectPublish", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId int64

		resp, httpRes, err := apiClient.ProjectsAPI.PrivateProjectPublish(context.Background(), projectId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProjectsAPIService PrivateProjectUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId int64

		httpRes, err := apiClient.ProjectsAPI.PrivateProjectUpdate(context.Background(), projectId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProjectsAPIService PrivateProjectsList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ProjectsAPI.PrivateProjectsList(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProjectsAPIService PrivateProjectsSearch", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ProjectsAPI.PrivateProjectsSearch(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProjectsAPIService ProjectArticles", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId int64

		resp, httpRes, err := apiClient.ProjectsAPI.ProjectArticles(context.Background(), projectId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProjectsAPIService ProjectDetails", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId int64

		resp, httpRes, err := apiClient.ProjectsAPI.ProjectDetails(context.Background(), projectId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProjectsAPIService ProjectsList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ProjectsAPI.ProjectsList(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProjectsAPIService ProjectsSearch", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ProjectsAPI.ProjectsSearch(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
